alts_fit_filters: (non_residential_sqft>0) & (large_area_id == 115)
alts_predict_filters: large_area_id == 115
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (slid == 1600115) & (home_based_status ==
  0)
choosers_predict_filters: (slid == 1600115) & (home_based_status == 0)
estimation_sample_size: 5000
fit_parameters:
  Coefficient: {st_b_ln_non_residential_sqft: -0.45953330021581, st_building_age: -0.2905497679743922,
    st_building_type_id_is_26: 0.040565278715521416, st_is_retail: 0.34270402249434995,
    st_jobs_within_30_min: -0.02164543795599953, st_stories: 0.0030170692495682977,
    st_zones_ln_empden_16: 0.13103939678808732, st_zones_popden: -0.05758291549894593}
  Std. Error: {st_b_ln_non_residential_sqft: 0.00822408097129312, st_building_age: 0.015847962287488502,
    st_building_type_id_is_26: 0.0021221753420614083, st_is_retail: 0.006456021213702005,
    st_jobs_within_30_min: 0.01806234233450746, st_stories: 0.0017836349752008783,
    st_zones_ln_empden_16: 0.004272385976310079, st_zones_popden: 0.011711843320116946}
  T-Score: {st_b_ln_non_residential_sqft: -55.876553479939155, st_building_age: -18.333572651404694,
    st_building_type_id_is_26: 19.11495148940789, st_is_retail: 53.08285260386202,
    st_jobs_within_30_min: -1.1983738075125892, st_stories: 1.6915284189403756, st_zones_ln_empden_16: 30.671244947129473,
    st_zones_popden: -4.916639842682847}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -11985.101604852936, 'null': -17005.986908309435, ratio: 0.29524221855087995}
model_expression: [st_is_retail, st_building_type_id_is_26, st_stories, st_b_ln_non_residential_sqft,
  st_zones_ln_empden_16, st_jobs_within_30_min, st_zones_popden, st_building_age]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 30
