alts_fit_filters: (non_residential_sqft>0) & (large_area_id == 3)
alts_predict_filters: large_area_id == 3
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (slid == 200003) & (home_based_status == 0)
choosers_predict_filters: (slid == 200003) & (home_based_status == 0)
estimation_sample_size: 5000
fit_parameters:
  Coefficient: {st_b_ln_non_residential_sqft: -1.1880108029435, st_building_age: -0.20846212450211482,
    st_is_industrial: 0.1055947116571881, st_is_office: 0.06192027492763508, st_jobs_within_30_min: -0.18690921668607355,
    st_zones_ln_empden_2: 0.1874548184006651, st_zones_popden: -0.1411592533631501}
  Std. Error: {st_b_ln_non_residential_sqft: 0.0065240438440655945, st_building_age: 0.019485782796625467,
    st_is_industrial: 0.0033666935171003205, st_is_office: 0.0037954588401460073,
    st_jobs_within_30_min: 0.018548494412478782, st_zones_ln_empden_2: 0.0050318023572227845,
    st_zones_popden: 0.018875952552568086}
  T-Score: {st_b_ln_non_residential_sqft: -182.0973051896546, st_building_age: -10.698165256066394,
    st_is_industrial: 31.36451569495258, st_is_office: 16.31430547281421, st_jobs_within_30_min: -10.076786424257028,
    st_zones_ln_empden_2: 37.25401060945635, st_zones_popden: -7.47825853927278}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -14098.94750254871, 'null': -17005.986908309435, ratio: 0.17094211711643104}
model_expression: [st_is_office, st_is_industrial, st_b_ln_non_residential_sqft, st_zones_ln_empden_2,
  st_jobs_within_30_min, st_zones_popden, st_building_age]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 30
