name: hlcm130003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 13

choosers_predict_filters: hh_type_large_area_id == 130003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.05062803790692763
        st_building_age: -0.04215932193690433
        st_city_id_is_1005: 0.07316930318183651
        st_city_id_is_1010: 0.04129304796020222
        st_city_id_is_1015: 0.04327525014297482
        st_city_id_is_1020: 0.03622549461748669
        st_city_id_is_1025: -0.015677431368121945
        st_city_id_is_1030: -0.1030685634050823
        st_city_id_is_1040: 0.0014429877528532103
        st_city_id_is_1045: 0.06052245066381116
        st_city_id_is_1050: 0.017816694260615853
        st_city_id_is_1055: 0.05564030564564962
        st_city_id_is_1060: -0.016244623723336522
        st_city_id_is_1065: 0.05930213673538098
        st_city_id_is_1070: -0.042560843752345874
        st_city_id_is_1075: 0.013156263214350188
        st_city_id_is_1080: 0.03446410270218012
        st_city_id_is_1085: -0.1668866627347397
        st_city_id_is_1090: 0.002538260142484319
        st_city_id_is_1095: 0.035548626556594826
        st_city_id_is_1100: 0.009639363857713454
        st_city_id_is_1105: 0.05403183458503542
        st_city_id_is_1110: -0.03878858859905987
        st_city_id_is_1115: -0.004535713035360856
        st_city_id_is_1120: 0.06754884362487128
        st_city_id_is_1125: 0.03346846085645553
        st_city_id_is_1130: 0.0334494918098309
        st_city_id_is_1135: -0.03221884151826336
        st_city_id_is_1140: 0.056314762544761726
        st_city_id_is_1145: -0.03959917864821665
        st_city_id_is_1150: 0.043287866298095654
        st_city_id_is_1155: 0.011429565005791774
        st_city_id_is_1160: 0.040434853821275756
        st_city_id_is_1165: 0.04813102226164386
        st_city_id_is_1170: -0.03337844919251626
        st_city_id_is_1175: 0.020448024896405844
        st_city_id_is_1180: -0.0014796515575523036
        st_city_id_is_1185: -0.032845692555090684
        st_city_id_is_1190: 0.01789237960876045
        st_city_id_is_1200: 0.01044863049666598
        st_city_id_is_1205: 0.02290041122880754
        st_city_id_is_1210: 0.024334516221876042
        st_city_id_is_1215: 0.07065776752873748
        st_city_id_is_1220: 0.024046045655103026
        st_jobs_within_30_min: -0.04659575769700834
        st_ln_empden: -0.03948820730019598
        st_ln_residential_units: 0.05050095328714728
        st_mean_zonal_hhsize: -0.034376816704679194
        st_mode_income_quartile_is_4: 0.04664027939551314
        st_popden: -0.045269018200538906
        st_zone_mean_age_of_head: -0.04180287554004716
        st_zone_prop_race_1: -0.009948812870689733
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07111453577653938
        st_building_age: 0.02511329585258624
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03795501544468464
        st_ln_empden: 0.031024737109748617
        st_ln_residential_units: 0.009228306625037758
        st_mean_zonal_hhsize: 0.028395394959054642
        st_mode_income_quartile_is_4: 0.026744713150582904
        st_popden: 0.0376030176934427
        st_zone_mean_age_of_head: 0.028538204279641103
        st_zone_prop_race_1: 0.04168058466023301
    T-Score:
        st_b_ln_sqft_per_unit: 21.99053863251124
        st_building_age: -1.501135188475295
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 1.9261615609705527
        st_ln_empden: 0.9866593282185531
        st_ln_residential_units: 40.61250688348139
        st_mean_zonal_hhsize: -8.579724038606578
        st_mode_income_quartile_is_4: 15.306635081508418
        st_popden: -0.9104245951428086
        st_zone_mean_age_of_head: 12.072269383319547
        st_zone_prop_race_1: 3.677583029167535

probability_mode: single_chooser

log_likelihoods:
    convergence: -12690.490758464182
    'null': -13815.510557964428
    ratio: 0.08143164849247564
