name: hlcm160003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 16

choosers_predict_filters: hh_type_large_area_id == 160003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.09298828572971471
        st_building_age: -0.07992462534059361
        st_city_id_is_1005: 0.04918064086407903
        st_city_id_is_1010: 0.04716998988298967
        st_city_id_is_1015: 0.07005944708001527
        st_city_id_is_1020: 0.08266730751876775
        st_city_id_is_1025: 0.019549121723784552
        st_city_id_is_1030: 0.0054502243960245994
        st_city_id_is_1040: 0.013556327016007444
        st_city_id_is_1045: 0.048331757674468886
        st_city_id_is_1050: 0.022759571474915676
        st_city_id_is_1055: 0.05358304674015271
        st_city_id_is_1060: 0.04523220439027118
        st_city_id_is_1065: 0.07562050868532212
        st_city_id_is_1070: 0.09428593151270821
        st_city_id_is_1075: 0.05656617807001771
        st_city_id_is_1080: -0.07230967720547318
        st_city_id_is_1085: 0.07896551409187996
        st_city_id_is_1090: 0.019434370150770444
        st_city_id_is_1095: 0.050365763873432313
        st_city_id_is_1100: 0.03291267761170371
        st_city_id_is_1105: 0.048974122741812044
        st_city_id_is_1110: -0.14952119804082983
        st_city_id_is_1115: 0.00026400059328527016
        st_city_id_is_1120: -0.09402577599293432
        st_city_id_is_1125: 0.041473679752746725
        st_city_id_is_1130: 0.044269655600277104
        st_city_id_is_1135: 0.005006330415091828
        st_city_id_is_1140: 0.07199947736322132
        st_city_id_is_1145: -0.007613578643329969
        st_city_id_is_1150: 0.01388427289696137
        st_city_id_is_1155: 0.030050638092873384
        st_city_id_is_1160: 0.06952415737704937
        st_city_id_is_1165: 0.05211529744141605
        st_city_id_is_1170: -0.0962944850638282
        st_city_id_is_1175: 0.09006260858169343
        st_city_id_is_1180: -0.013569874512225993
        st_city_id_is_1185: -0.16315312652428415
        st_city_id_is_1190: 0.07195369743570444
        st_city_id_is_1200: 0.016777125859629045
        st_city_id_is_1205: 0.024851503950759118
        st_city_id_is_1210: -0.1482130408328433
        st_city_id_is_1215: 0.09663692745481285
        st_city_id_is_1220: 0.06258677865591677
        st_jobs_within_30_min: -0.0590956420707514
        st_ln_empden: -0.06226519530256123
        st_ln_residential_units: 0.03593761773208324
        st_mean_zonal_hhsize: 0.10627423453018127
        st_mode_income_quartile_is_4: 0.09276996061982791
        st_popden: -0.05093756939528364
        st_zone_mean_age_of_head: -0.06874213111311582
        st_zone_prop_race_1: 0.042229081836476653
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0699773382448247
        st_building_age: 0.027008833793184882
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.04032901975144966
        st_ln_empden: 0.034479683860339394
        st_ln_residential_units: 0.012453626667610723
        st_mean_zonal_hhsize: 0.02751265186347744
        st_mode_income_quartile_is_4: 0.02723132012841858
        st_popden: 0.039968346481020565
        st_zone_mean_age_of_head: 0.0332707517453326
        st_zone_prop_race_1: 0.0356745922026284
    T-Score:
        st_b_ln_sqft_per_unit: 17.309195562458918
        st_building_age: -1.1258499200212344
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 3.2840382129699957
        st_ln_empden: -1.1455620157898143
        st_ln_residential_units: 23.92527807690541
        st_mean_zonal_hhsize: 4.292421170197224
        st_mode_income_quartile_is_4: 10.32574667162389
        st_popden: 1.1308520671124531
        st_zone_mean_age_of_head: 15.520314169582292
        st_zone_prop_race_1: -0.49373668728519127

probability_mode: single_chooser

log_likelihoods:
    convergence: -13194.039370967603
    'null': -13815.510557964428
    ratio: 0.04498358452909701
