name: hlcm120003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 12

choosers_predict_filters: hh_type_large_area_id == 120003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.04438547996175731
        st_building_age: 0.05123824848046121
        st_city_id_is_1005: 0.01286434618548797
        st_city_id_is_1010: -0.0016955903421055568
        st_city_id_is_1015: 0.0023032870702522743
        st_city_id_is_1020: -0.03309481196935436
        st_city_id_is_1025: 0.07123444815501348
        st_city_id_is_1030: 0.02133697710157731
        st_city_id_is_1040: -0.03208838828239652
        st_city_id_is_1045: 0.027934502579917964
        st_city_id_is_1050: -0.015418661306529014
        st_city_id_is_1055: -0.004092915358753438
        st_city_id_is_1060: -0.031444418005548126
        st_city_id_is_1065: 0.025993158555651583
        st_city_id_is_1070: -0.07439103941891427
        st_city_id_is_1075: -0.014989827878572254
        st_city_id_is_1080: -0.006471456693856952
        st_city_id_is_1085: -0.029218756356236823
        st_city_id_is_1090: -0.001526978918171204
        st_city_id_is_1095: -0.032093570144616126
        st_city_id_is_1100: -0.001042645229396638
        st_city_id_is_1105: 0.021041148662430186
        st_city_id_is_1110: -0.017341398635196282
        st_city_id_is_1115: -0.008657060432309845
        st_city_id_is_1120: 0.017527534270099076
        st_city_id_is_1125: 0.02505146950310192
        st_city_id_is_1130: -0.007027466763397044
        st_city_id_is_1135: -0.05539950461767069
        st_city_id_is_1140: -0.018852489425321493
        st_city_id_is_1145: -0.08352677728221752
        st_city_id_is_1150: -0.024110957891569508
        st_city_id_is_1155: -0.030088879701337477
        st_city_id_is_1160: 0.05755527934404054
        st_city_id_is_1165: -0.0021249305855956346
        st_city_id_is_1170: -0.005285987912010265
        st_city_id_is_1175: 0.04669840086222647
        st_city_id_is_1180: -0.029574579812170883
        st_city_id_is_1185: 0.02214347452343611
        st_city_id_is_1190: 0.01421255241405119
        st_city_id_is_1200: 0.009163919080850772
        st_city_id_is_1205: -0.10293368163371867
        st_city_id_is_1210: 0.03437382272336559
        st_city_id_is_1215: 0.06867503240057289
        st_city_id_is_1220: 0.013035978436882232
        st_jobs_within_30_min: 0.0507685530133286
        st_ln_empden: 0.05076869097786854
        st_ln_residential_units: -0.04843794875431113
        st_mean_zonal_hhsize: 0.02174306484061965
        st_mode_income_quartile_is_3: 0.04362566860290622
        st_popden: 0.05383655329379794
        st_zone_mean_age_of_head: 0.019485821238215895
        st_zone_prop_race_1: 0.033289865183087776
    Std. Error:
        st_b_ln_sqft_per_unit: 0.08914661579778699
        st_building_age: 0.026785030082916293
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03628420794327688
        st_ln_empden: 0.030756739855587644
        st_ln_residential_units: 0.007675778575347038
        st_mean_zonal_hhsize: 0.023773125265980247
        st_mode_income_quartile_is_3: 0.02288228961790935
        st_popden: 0.021483837173854853
        st_zone_mean_age_of_head: 0.02503924550763738
        st_zone_prop_race_1: 0.03465342934465543
    T-Score:
        st_b_ln_sqft_per_unit: -9.305109334427671
        st_building_age: 1.5816960676904823
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: -0.7127914685455171
        st_ln_empden: -1.4339330681109113
        st_ln_residential_units: 49.973275146220104
        st_mean_zonal_hhsize: 4.420479824773616
        st_mode_income_quartile_is_3: 1.6416425692259715
        st_popden: -0.2364646653285882
        st_zone_mean_age_of_head: -11.162047910190614
        st_zone_prop_race_1: 6.538316054121442

probability_mode: single_chooser

log_likelihoods:
    convergence: -12760.152461725127
    'null': -13815.510557964428
    ratio: 0.07638936627144066
