name: hlcm90003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 9

choosers_predict_filters: hh_type_large_area_id == 90003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.04490664472537728
        st_building_age: 0.04403756852508372
        st_city_id_is_1005: -0.005596435978590892
        st_city_id_is_1010: -0.03890876597156913
        st_city_id_is_1015: 0.016720562446548255
        st_city_id_is_1020: -0.023941605535161267
        st_city_id_is_1025: -0.023347359597321638
        st_city_id_is_1030: -0.029973361341319303
        st_city_id_is_1040: -0.06231287871295222
        st_city_id_is_1045: -0.022655020833364254
        st_city_id_is_1050: 0.0025931496791378006
        st_city_id_is_1055: 0.013672617957263197
        st_city_id_is_1060: -0.04333671463829585
        st_city_id_is_1065: 0.02468902866839918
        st_city_id_is_1070: -0.030042271356342402
        st_city_id_is_1075: -0.009240897762273964
        st_city_id_is_1080: -0.00732704855921673
        st_city_id_is_1085: -0.004327958931241115
        st_city_id_is_1090: -0.06013374305710724
        st_city_id_is_1095: -0.006635593445402913
        st_city_id_is_1100: -0.03193828646138132
        st_city_id_is_1105: 0.014602156356714548
        st_city_id_is_1110: -0.017646784374107983
        st_city_id_is_1115: -0.048903055046430915
        st_city_id_is_1120: 0.019911701240596855
        st_city_id_is_1125: -0.01541885323336238
        st_city_id_is_1130: -0.09722695655394613
        st_city_id_is_1135: -0.04798838247957149
        st_city_id_is_1140: 0.02088915178229899
        st_city_id_is_1145: -0.03532518823702464
        st_city_id_is_1150: -0.005924115292408465
        st_city_id_is_1155: -0.10136880022652096
        st_city_id_is_1160: 0.015395196432363388
        st_city_id_is_1165: -0.011717982302587093
        st_city_id_is_1170: -0.02671361159558926
        st_city_id_is_1175: 0.03023746092243814
        st_city_id_is_1180: -0.03565365179277411
        st_city_id_is_1185: 0.026296182394396288
        st_city_id_is_1190: -0.005937277149095213
        st_city_id_is_1200: 0.009934951562404964
        st_city_id_is_1205: -0.008345039774326279
        st_city_id_is_1210: 0.055905520913797586
        st_city_id_is_1215: 0.07131759227887667
        st_city_id_is_1220: -0.03421151767569324
        st_jobs_within_30_min: -0.06757235883012537
        st_ln_empden: 0.021575514128617492
        st_ln_residential_units: 0.035604234137721416
        st_mean_zonal_hhsize: -0.04500177449433811
        st_mode_income_quartile_is_3: 0.04577455321135333
        st_popden: -0.008554994155452416
        st_zone_mean_age_of_head: -0.0233990563382448
        st_zone_prop_race_1: 0.0325780222423203
    Std. Error:
        st_b_ln_sqft_per_unit: 0.10110280741636761
        st_building_age: 0.02711645091265803
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03223654666695805
        st_ln_empden: 0.024698689301459523
        st_ln_residential_units: 0.00669757369348417
        st_mean_zonal_hhsize: 0.026059127921273715
        st_mode_income_quartile_is_3: 0.0232392735755458
        st_popden: 0.021094707878321965
        st_zone_mean_age_of_head: 0.02011928807573498
        st_zone_prop_race_1: 0.034109108441582645
    T-Score:
        st_b_ln_sqft_per_unit: -7.800522020268793
        st_building_age: 0.11116827484099778
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 3.306588515197893
        st_ln_empden: -0.7086358531363736
        st_ln_residential_units: 66.44071554821633
        st_mean_zonal_hhsize: -11.615534447084944
        st_mode_income_quartile_is_3: 1.5986140835352127
        st_popden: -5.195782658828813
        st_zone_mean_age_of_head: -20.803550190678795
        st_zone_prop_race_1: 10.2361843027242

probability_mode: single_chooser

log_likelihoods:
    convergence: -10783.63471617344
    'null': -13815.510557964428
    ratio: 0.2194544913175981
