name: hlcm20125

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 2

choosers_predict_filters: hh_type_large_area_id == 20125

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_2005
- st_city_id_is_2010
- st_city_id_is_2015
- st_city_id_is_2020
- st_city_id_is_2025
- st_city_id_is_2030
- st_city_id_is_2035
- st_city_id_is_2040
- st_city_id_is_2045
- st_city_id_is_2050
- st_city_id_is_2055
- st_city_id_is_2060
- st_city_id_is_2065
- st_city_id_is_2072
- st_city_id_is_2075
- st_city_id_is_2080
- st_city_id_is_2085
- st_city_id_is_2090
- st_city_id_is_2095
- st_city_id_is_2100
- st_city_id_is_2105
- st_city_id_is_2110
- st_city_id_is_2115
- st_city_id_is_2120
- st_city_id_is_2125
- st_city_id_is_2130
- st_city_id_is_2135
- st_city_id_is_2140
- st_city_id_is_2145
- st_city_id_is_2150
- st_city_id_is_2155
- st_city_id_is_2160
- st_city_id_is_2165
- st_city_id_is_2170
- st_city_id_is_2175
- st_city_id_is_2180
- st_city_id_is_2185
- st_city_id_is_2190
- st_city_id_is_2195
- st_city_id_is_2200
- st_city_id_is_2205
- st_city_id_is_2210
- st_city_id_is_2215
- st_city_id_is_2220
- st_city_id_is_2230
- st_city_id_is_2235
- st_city_id_is_2240
- st_city_id_is_2245
- st_city_id_is_2250
- st_city_id_is_2255
- st_city_id_is_2260
- st_city_id_is_2265
- st_city_id_is_2270
- st_city_id_is_2275
- st_city_id_is_2280
- st_city_id_is_2285
- st_city_id_is_2290
- st_city_id_is_2295
- st_city_id_is_2300
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_1
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.04982461323762352
        st_building_age: 0.04932446530338181
        st_city_id_is_2005: 0.018147244055085224
        st_city_id_is_2010: -0.02522594811382128
        st_city_id_is_2015: -0.015206886516082811
        st_city_id_is_2020: 0.02243494722031738
        st_city_id_is_2025: 0.0008760991897934202
        st_city_id_is_2030: -0.024123782876053178
        st_city_id_is_2035: -0.10804546711569446
        st_city_id_is_2040: -0.04307422480115195
        st_city_id_is_2045: -0.022241824182653438
        st_city_id_is_2050: -0.03816815949544964
        st_city_id_is_2055: 0.024780287849831037
        st_city_id_is_2060: -0.026844764532946826
        st_city_id_is_2065: 0.029267447715895487
        st_city_id_is_2072: 0.0418320269614317
        st_city_id_is_2075: -0.06722779640110052
        st_city_id_is_2080: -0.047757303524925944
        st_city_id_is_2085: -0.05681376755871857
        st_city_id_is_2090: 0.012433268399337994
        st_city_id_is_2095: -0.03396428089588407
        st_city_id_is_2100: 0.043959333110273405
        st_city_id_is_2105: -0.03698491452434078
        st_city_id_is_2110: -0.049026244979377
        st_city_id_is_2115: -0.04077899725830473
        st_city_id_is_2120: 0.012731909314384192
        st_city_id_is_2125: 0.012514796646378726
        st_city_id_is_2130: 0.012622738175865018
        st_city_id_is_2135: -0.022445312341116942
        st_city_id_is_2140: 0.0027863173536833074
        st_city_id_is_2145: -0.08214347791570549
        st_city_id_is_2150: 0.06634873386575568
        st_city_id_is_2155: -0.003453590327944116
        st_city_id_is_2160: -0.033329390905901146
        st_city_id_is_2165: -0.01323634734853703
        st_city_id_is_2170: -0.03594603509671712
        st_city_id_is_2175: -0.04773813738727035
        st_city_id_is_2180: 0.03218313595769764
        st_city_id_is_2185: -0.008801331712542347
        st_city_id_is_2190: -0.027286315735931235
        st_city_id_is_2195: 0.013208758602112586
        st_city_id_is_2200: 0.0012677427366465396
        st_city_id_is_2205: -0.01963920860958982
        st_city_id_is_2210: 0.011074145768150096
        st_city_id_is_2215: 0.03861306196539549
        st_city_id_is_2220: -0.009254782487879084
        st_city_id_is_2230: 0.0152390522276113
        st_city_id_is_2235: -0.014274893723402602
        st_city_id_is_2240: -0.006697585585209617
        st_city_id_is_2245: -0.05179820179654607
        st_city_id_is_2250: 0.07742057407237922
        st_city_id_is_2255: 0.01643659060855796
        st_city_id_is_2260: -0.03944027807169053
        st_city_id_is_2265: -0.0033432054659753
        st_city_id_is_2270: -0.001959458513510491
        st_city_id_is_2275: 0.02816671659683843
        st_city_id_is_2280: 0.06804908387309569
        st_city_id_is_2285: -0.04173023009134781
        st_city_id_is_2290: 0.03482694543850318
        st_city_id_is_2295: 0.01193871535543871
        st_city_id_is_2300: 0.011519085443064014
        st_jobs_within_30_min: 0.057610931420599254
        st_ln_empden: 0.054460166502593346
        st_ln_residential_units: 0.05047002801907389
        st_mean_zonal_hhsize: -0.04912250883349489
        st_mode_income_quartile_is_1: 0.038053752176141965
        st_popden: 0.04695269978122279
        st_zone_mean_age_of_head: -0.00805278955709858
        st_zone_prop_race_1: -0.054189037944438564
    Std. Error:
        st_b_ln_sqft_per_unit: 0.09652975139963209
        st_building_age: 0.02718409731213641
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 0.03533537275267524
        st_ln_empden: 0.028895156306026393
        st_ln_residential_units: 0.0064407376101322964
        st_mean_zonal_hhsize: 0.025253925396126305
        st_mode_income_quartile_is_1: 0.026674489138600082
        st_popden: 0.022770543534857166
        st_zone_mean_age_of_head: 0.026520887126616956
        st_zone_prop_race_1: 0.03236856976391456
    T-Score:
        st_b_ln_sqft_per_unit: -14.34063732419352
        st_building_age: 2.2095593589602256
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: -1.8726769491096764
        st_ln_empden: -0.048843353510058925
        st_ln_residential_units: 64.97492072668696
        st_mean_zonal_hhsize: -4.415417941664101
        st_mode_income_quartile_is_1: 7.402953876612925
        st_popden: -0.9348877160919243
        st_zone_mean_age_of_head: 0.9509962575588654
        st_zone_prop_race_1: -4.368260772867309

probability_mode: single_chooser

log_likelihoods:
    convergence: -11606.288621353506
    'null': -13815.510557964428
    ratio: 0.15990881606162144
