name: hlcm120005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 12

choosers_predict_filters: hh_type_large_area_id == 120005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.04729373751586732
        st_building_age: 0.06079930358066539
        st_city_id_is_501: 0.0009114170904346286
        st_city_id_is_502: 0.07966356930248636
        st_city_id_is_503: 0.026233103348237682
        st_city_id_is_504: 0.021869471074753247
        st_city_id_is_505: 0.050610013773863996
        st_city_id_is_506: 0.0016252506024085139
        st_city_id_is_507: 0.006698707576999734
        st_city_id_is_508: 0.01733050455883421
        st_city_id_is_509: 0.07878987930151912
        st_city_id_is_510: -0.011948408486418025
        st_city_id_is_511: -0.069909051715452
        st_city_id_is_512: 0.03140046245357471
        st_city_id_is_513: 0.007459619316466537
        st_city_id_is_514: -0.030571715045142583
        st_city_id_is_515: 0.014198548351690888
        st_city_id_is_516: -0.019827921844196947
        st_city_id_is_517: -0.04864090546894046
        st_city_id_is_518: 0.007796551788822277
        st_city_id_is_519: 0.024068033527776568
        st_city_id_is_520: 0.024237780990388893
        st_city_id_is_521: -0.04789488894212043
        st_city_id_is_522: -0.06645431584392933
        st_city_id_is_523: 0.005665276053713919
        st_city_id_is_524: 0.05267594709799784
        st_city_id_is_525: 0.0017156215715761944
        st_city_id_is_526: 0.025980783698628305
        st_city_id_is_527: -0.04209799101473282
        st_city_id_is_528: 0.012806937792982155
        st_city_id_is_529: -0.0024656894825555564
        st_city_id_is_530: 0.015869243806908066
        st_city_id_is_531: 0.040278354629498
        st_city_id_is_532: 0.03573371397666835
        st_city_id_is_533: 0.029058914179912885
        st_city_id_is_534: -0.04027022120543831
        st_city_id_is_535: -0.03940408698920539
        st_city_id_is_536: -0.04825702308553025
        st_city_id_is_537: 0.004351858729363722
        st_city_id_is_538: 0.013018552368262895
        st_city_id_is_539: -0.031194285135579477
        st_city_id_is_540: 0.04247323389799368
        st_city_id_is_541: 0.05807624649085453
        st_city_id_is_542: -0.010452607423801294
        st_city_id_is_543: 0.003832348705337952
        st_city_id_is_544: -0.052554439707821636
        st_city_id_is_545: 0.07782433434701194
        st_city_id_is_546: 0.041724859120770494
        st_city_id_is_547: -0.00875146998167332
        st_city_id_is_548: -0.019563668814103916
        st_city_id_is_549: -0.030057292285446208
        st_city_id_is_550: -0.04061946495552869
        st_city_id_is_551: 0.007823100330954883
        st_city_id_is_552: -0.018405429632467784
        st_city_id_is_553: -0.039892752088349116
        st_city_id_is_554: 0.025323635928535405
        st_city_id_is_555: -0.0009433313362231978
        st_jobs_within_30_min: 0.06491364392973101
        st_ln_empden: 0.046754129002497404
        st_ln_residential_units: 0.025194233960708697
        st_mean_zonal_hhsize: 0.06718164664126271
        st_mode_income_quartile_is_3: 0.0737015295366869
        st_popden: 0.06720242415183734
        st_zone_mean_age_of_head: -0.009891510370911065
        st_zone_prop_race_1: 0.01506858976368869
    Std. Error:
        st_b_ln_sqft_per_unit: 0.08914661579778699
        st_building_age: 0.026785030082916293
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.03628420794327688
        st_ln_empden: 0.030756739855587644
        st_ln_residential_units: 0.007675778575347038
        st_mean_zonal_hhsize: 0.023773125265980247
        st_mode_income_quartile_is_3: 0.02288228961790935
        st_popden: 0.021483837173854853
        st_zone_mean_age_of_head: 0.02503924550763738
        st_zone_prop_race_1: 0.03465342934465543
    T-Score:
        st_b_ln_sqft_per_unit: -9.305109334427671
        st_building_age: 1.5816960676904823
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: -0.7127914685455171
        st_ln_empden: -1.4339330681109113
        st_ln_residential_units: 49.973275146220104
        st_mean_zonal_hhsize: 4.420479824773616
        st_mode_income_quartile_is_3: 1.6416425692259715
        st_popden: -0.2364646653285882
        st_zone_mean_age_of_head: -11.162047910190614
        st_zone_prop_race_1: 6.538316054121442

probability_mode: single_chooser

log_likelihoods:
    convergence: -12760.152461725127
    'null': -13815.510557964428
    ratio: 0.07638936627144066
