name: hlcm160125

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 16

choosers_predict_filters: hh_type_large_area_id == 160125

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_2005
- st_city_id_is_2010
- st_city_id_is_2015
- st_city_id_is_2020
- st_city_id_is_2025
- st_city_id_is_2030
- st_city_id_is_2035
- st_city_id_is_2040
- st_city_id_is_2045
- st_city_id_is_2050
- st_city_id_is_2055
- st_city_id_is_2060
- st_city_id_is_2065
- st_city_id_is_2072
- st_city_id_is_2075
- st_city_id_is_2080
- st_city_id_is_2085
- st_city_id_is_2090
- st_city_id_is_2095
- st_city_id_is_2100
- st_city_id_is_2105
- st_city_id_is_2110
- st_city_id_is_2115
- st_city_id_is_2120
- st_city_id_is_2125
- st_city_id_is_2130
- st_city_id_is_2135
- st_city_id_is_2140
- st_city_id_is_2145
- st_city_id_is_2150
- st_city_id_is_2155
- st_city_id_is_2160
- st_city_id_is_2165
- st_city_id_is_2170
- st_city_id_is_2175
- st_city_id_is_2180
- st_city_id_is_2185
- st_city_id_is_2190
- st_city_id_is_2195
- st_city_id_is_2200
- st_city_id_is_2205
- st_city_id_is_2210
- st_city_id_is_2215
- st_city_id_is_2220
- st_city_id_is_2230
- st_city_id_is_2235
- st_city_id_is_2240
- st_city_id_is_2245
- st_city_id_is_2250
- st_city_id_is_2255
- st_city_id_is_2260
- st_city_id_is_2265
- st_city_id_is_2270
- st_city_id_is_2275
- st_city_id_is_2280
- st_city_id_is_2285
- st_city_id_is_2290
- st_city_id_is_2295
- st_city_id_is_2300
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.15489950039472444
        st_building_age: -0.14333681850392366
        st_city_id_is_2005: 0.037999048928134
        st_city_id_is_2010: 0.05052937127690048
        st_city_id_is_2015: 0.07606566938816389
        st_city_id_is_2020: 0.05489101671125453
        st_city_id_is_2025: 0.011911620736825805
        st_city_id_is_2030: 0.08389839776837117
        st_city_id_is_2035: 0.028757150140699426
        st_city_id_is_2040: 0.02268460846685538
        st_city_id_is_2045: 0.038031383565379086
        st_city_id_is_2050: 0.03136034782724265
        st_city_id_is_2055: 0.05224227400250919
        st_city_id_is_2060: 0.06101484369709468
        st_city_id_is_2065: 0.0673777018424319
        st_city_id_is_2072: 0.04312632283313598
        st_city_id_is_2075: 0.05879613496868331
        st_city_id_is_2080: 0.03902911905671873
        st_city_id_is_2085: 0.032842549085986834
        st_city_id_is_2090: 0.002754021587471178
        st_city_id_is_2095: 0.016203362775830767
        st_city_id_is_2100: 0.042653048312487694
        st_city_id_is_2105: 0.025417163989651905
        st_city_id_is_2110: 0.04079339617637133
        st_city_id_is_2115: 0.02502275032832994
        st_city_id_is_2120: 0.04214383692864505
        st_city_id_is_2125: 0.01943852310414746
        st_city_id_is_2130: 0.03695371779416314
        st_city_id_is_2135: 0.03292593461393498
        st_city_id_is_2140: 0.031182397901377674
        st_city_id_is_2145: -0.023149920518598533
        st_city_id_is_2150: -0.02132974556536804
        st_city_id_is_2155: 0.03794243043741131
        st_city_id_is_2160: 0.008803500621667905
        st_city_id_is_2165: 0.020944083886649714
        st_city_id_is_2170: 0.07306828096960301
        st_city_id_is_2175: -0.031263580347863466
        st_city_id_is_2180: -0.18305891035086497
        st_city_id_is_2185: 0.03739867751222236
        st_city_id_is_2190: 0.04447847981972315
        st_city_id_is_2195: 0.04034719320190632
        st_city_id_is_2200: 0.03020337232571969
        st_city_id_is_2205: 0.020228504760405757
        st_city_id_is_2210: 0.04581041663315029
        st_city_id_is_2215: -0.1127330771920641
        st_city_id_is_2220: 0.03553473464956937
        st_city_id_is_2230: 0.08107303058353703
        st_city_id_is_2235: 0.013329777833459438
        st_city_id_is_2240: 0.096456456262017
        st_city_id_is_2245: 0.021153817758053507
        st_city_id_is_2250: 0.0856448595888375
        st_city_id_is_2255: 0.05954021140781664
        st_city_id_is_2260: 0.054851430979875444
        st_city_id_is_2265: 0.034853942639847035
        st_city_id_is_2270: 0.019436160484250727
        st_city_id_is_2275: 0.03967494377688569
        st_city_id_is_2280: 0.0748099485476663
        st_city_id_is_2285: -0.011680858655951245
        st_city_id_is_2290: 0.06396297155284884
        st_city_id_is_2295: 0.026820794916909755
        st_city_id_is_2300: 0.04999125375098033
        st_jobs_within_30_min: 0.04944766908764554
        st_ln_empden: 0.033313495467631904
        st_ln_residential_units: 0.06524753840810707
        st_mean_zonal_hhsize: -0.027939879304303302
        st_mode_income_quartile_is_4: 0.12068172064701489
        st_popden: -0.09556190363584306
        st_zone_mean_age_of_head: 0.12125523968674769
        st_zone_prop_race_1: 0.11590009738718694
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0699773382448247
        st_building_age: 0.027008833793184882
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 0.04032901975144966
        st_ln_empden: 0.034479683860339394
        st_ln_residential_units: 0.012453626667610723
        st_mean_zonal_hhsize: 0.02751265186347744
        st_mode_income_quartile_is_4: 0.02723132012841858
        st_popden: 0.039968346481020565
        st_zone_mean_age_of_head: 0.0332707517453326
        st_zone_prop_race_1: 0.0356745922026284
    T-Score:
        st_b_ln_sqft_per_unit: 17.309195562458918
        st_building_age: -1.1258499200212344
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 3.2840382129699957
        st_ln_empden: -1.1455620157898143
        st_ln_residential_units: 23.92527807690541
        st_mean_zonal_hhsize: 4.292421170197224
        st_mode_income_quartile_is_4: 10.32574667162389
        st_popden: 1.1308520671124531
        st_zone_mean_age_of_head: 15.520314169582292
        st_zone_prop_race_1: -0.49373668728519127

probability_mode: single_chooser

log_likelihoods:
    convergence: -13194.039370967603
    'null': -13815.510557964428
    ratio: 0.04498358452909701
