name: hlcm160005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 16

choosers_predict_filters: hh_type_large_area_id == 160005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.06810121105132101
        st_building_age: 0.12974493251546573
        st_city_id_is_501: 0.023628250119223513
        st_city_id_is_502: 0.11065344883874265
        st_city_id_is_503: 0.06664342949823372
        st_city_id_is_504: 0.016248159042213668
        st_city_id_is_505: -0.03413722846665549
        st_city_id_is_506: 0.005337968365663877
        st_city_id_is_507: 0.04613039877238078
        st_city_id_is_508: 0.024889574711852148
        st_city_id_is_509: 0.08406595929779623
        st_city_id_is_510: 0.013218344744294744
        st_city_id_is_511: 0.04126531422220428
        st_city_id_is_512: 0.0735434501458558
        st_city_id_is_513: 0.03976599121896106
        st_city_id_is_514: 0.013168569917070511
        st_city_id_is_515: 0.055834361203736076
        st_city_id_is_516: 0.02152845300069399
        st_city_id_is_517: 0.05199100732004142
        st_city_id_is_518: -0.010353423247808006
        st_city_id_is_519: 0.061076984872344794
        st_city_id_is_520: -7.362354844374217e-05
        st_city_id_is_521: 0.07339734408238599
        st_city_id_is_522: 0.0346633973787755
        st_city_id_is_523: 0.05249642997000895
        st_city_id_is_524: 0.07328348466869228
        st_city_id_is_525: -0.0388611703850728
        st_city_id_is_526: 0.0540010919630663
        st_city_id_is_527: 0.0629840807260218
        st_city_id_is_528: 0.03487784564926572
        st_city_id_is_529: 0.02033365540689027
        st_city_id_is_530: 0.012514433531133814
        st_city_id_is_531: 0.07244165833386541
        st_city_id_is_532: 0.03421140306330908
        st_city_id_is_533: -0.12247328921209662
        st_city_id_is_534: 0.051260099851304294
        st_city_id_is_535: 0.046759730095430614
        st_city_id_is_536: -0.13394744947974987
        st_city_id_is_537: 0.00692750506987519
        st_city_id_is_538: 0.028622918110087634
        st_city_id_is_539: -0.022230759296321772
        st_city_id_is_540: 0.13291618306985398
        st_city_id_is_541: 0.10987905760913019
        st_city_id_is_542: 0.0536907086199786
        st_city_id_is_543: 0.09553040101941222
        st_city_id_is_544: 0.06182103089433736
        st_city_id_is_545: 0.13371541327575154
        st_city_id_is_546: 0.01643608375651164
        st_city_id_is_547: 0.037425043736919836
        st_city_id_is_548: 0.011474840711891771
        st_city_id_is_549: 0.02840981042666841
        st_city_id_is_550: -0.10696930071228197
        st_city_id_is_551: 0.051346164271246636
        st_city_id_is_552: 0.03648714677946753
        st_city_id_is_553: 0.018753728373577597
        st_city_id_is_554: 0.010364836708062458
        st_city_id_is_555: -6.710263277235708e-05
        st_jobs_within_30_min: -0.06080495525109707
        st_ln_empden: 0.09040637785049234
        st_ln_residential_units: 0.04342165338422628
        st_mean_zonal_hhsize: 0.050641392442348596
        st_mode_income_quartile_is_4: 0.13112833501604745
        st_popden: 0.09972682018432645
        st_zone_mean_age_of_head: -0.050736146317592955
        st_zone_prop_race_1: 0.06716745299015922
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0699773382448247
        st_building_age: 0.027008833793184882
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.04032901975144966
        st_ln_empden: 0.034479683860339394
        st_ln_residential_units: 0.012453626667610723
        st_mean_zonal_hhsize: 0.02751265186347744
        st_mode_income_quartile_is_4: 0.02723132012841858
        st_popden: 0.039968346481020565
        st_zone_mean_age_of_head: 0.0332707517453326
        st_zone_prop_race_1: 0.0356745922026284
    T-Score:
        st_b_ln_sqft_per_unit: 17.309195562458918
        st_building_age: -1.1258499200212344
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 3.2840382129699957
        st_ln_empden: -1.1455620157898143
        st_ln_residential_units: 23.92527807690541
        st_mean_zonal_hhsize: 4.292421170197224
        st_mode_income_quartile_is_4: 10.32574667162389
        st_popden: 1.1308520671124531
        st_zone_mean_age_of_head: 15.520314169582292
        st_zone_prop_race_1: -0.49373668728519127

probability_mode: single_chooser

log_likelihoods:
    convergence: -13194.039370967603
    'null': -13815.510557964428
    ratio: 0.04498358452909701
