name: hlcm180125

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 18

choosers_predict_filters: hh_type_large_area_id == 180125

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_2005
- st_city_id_is_2010
- st_city_id_is_2015
- st_city_id_is_2020
- st_city_id_is_2025
- st_city_id_is_2030
- st_city_id_is_2035
- st_city_id_is_2040
- st_city_id_is_2045
- st_city_id_is_2050
- st_city_id_is_2055
- st_city_id_is_2060
- st_city_id_is_2065
- st_city_id_is_2072
- st_city_id_is_2075
- st_city_id_is_2080
- st_city_id_is_2085
- st_city_id_is_2090
- st_city_id_is_2095
- st_city_id_is_2100
- st_city_id_is_2105
- st_city_id_is_2110
- st_city_id_is_2115
- st_city_id_is_2120
- st_city_id_is_2125
- st_city_id_is_2130
- st_city_id_is_2135
- st_city_id_is_2140
- st_city_id_is_2145
- st_city_id_is_2150
- st_city_id_is_2155
- st_city_id_is_2160
- st_city_id_is_2165
- st_city_id_is_2170
- st_city_id_is_2175
- st_city_id_is_2180
- st_city_id_is_2185
- st_city_id_is_2190
- st_city_id_is_2195
- st_city_id_is_2200
- st_city_id_is_2205
- st_city_id_is_2210
- st_city_id_is_2215
- st_city_id_is_2220
- st_city_id_is_2230
- st_city_id_is_2235
- st_city_id_is_2240
- st_city_id_is_2245
- st_city_id_is_2250
- st_city_id_is_2255
- st_city_id_is_2260
- st_city_id_is_2265
- st_city_id_is_2270
- st_city_id_is_2275
- st_city_id_is_2280
- st_city_id_is_2285
- st_city_id_is_2290
- st_city_id_is_2295
- st_city_id_is_2300
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.08373034249572253
        st_building_age: 0.0010487018673438998
        st_city_id_is_2005: 0.05388782671399505
        st_city_id_is_2010: 0.010147448772512746
        st_city_id_is_2015: 0.045600694539266816
        st_city_id_is_2020: 0.05174433184549165
        st_city_id_is_2025: 0.04614769000253851
        st_city_id_is_2030: 0.025433103822915002
        st_city_id_is_2035: 0.04304932825216583
        st_city_id_is_2040: 0.01908626880942903
        st_city_id_is_2045: 0.029393970303260426
        st_city_id_is_2050: 0.04604569731532684
        st_city_id_is_2055: 0.06592627291899102
        st_city_id_is_2060: 0.03017333445006437
        st_city_id_is_2065: 0.05135276492179822
        st_city_id_is_2072: -0.029724066257918874
        st_city_id_is_2075: -0.03227037755240599
        st_city_id_is_2080: 0.05443158050343876
        st_city_id_is_2085: 0.042442996087521376
        st_city_id_is_2090: 0.05404681980132062
        st_city_id_is_2095: 0.028060167325304156
        st_city_id_is_2100: 0.04783601475651455
        st_city_id_is_2105: 0.03768794326550361
        st_city_id_is_2110: 0.0790798718959149
        st_city_id_is_2115: -0.010738347182421379
        st_city_id_is_2120: 0.04712545427220966
        st_city_id_is_2125: 0.040158018727210205
        st_city_id_is_2130: 0.05756705353104532
        st_city_id_is_2135: 0.07048225853957545
        st_city_id_is_2140: 0.03900332058902763
        st_city_id_is_2145: -0.06759712306168077
        st_city_id_is_2150: 0.03847524433360165
        st_city_id_is_2155: 0.05644559396406323
        st_city_id_is_2160: 0.048948567614763766
        st_city_id_is_2165: 0.05321067789389331
        st_city_id_is_2170: 0.08908307513180488
        st_city_id_is_2175: 0.008180812824889182
        st_city_id_is_2180: -0.012249741510174602
        st_city_id_is_2185: 0.06129062811549274
        st_city_id_is_2190: 0.017319283496440893
        st_city_id_is_2195: 0.05808392727631405
        st_city_id_is_2200: 0.057338858343463625
        st_city_id_is_2205: 0.024682435899550086
        st_city_id_is_2210: 0.06990578457021808
        st_city_id_is_2215: -0.0550350392240793
        st_city_id_is_2220: -0.18919371063889187
        st_city_id_is_2230: 0.07073854349050629
        st_city_id_is_2235: 0.03965178045652259
        st_city_id_is_2240: -0.11122271135715493
        st_city_id_is_2245: 0.044429978676812414
        st_city_id_is_2250: 0.059835287879341836
        st_city_id_is_2255: 0.02451558538448526
        st_city_id_is_2260: 0.0643247564820469
        st_city_id_is_2265: 0.055797802428166024
        st_city_id_is_2270: 0.03130288926530207
        st_city_id_is_2275: 0.04789676200908356
        st_city_id_is_2280: -0.048670582485092755
        st_city_id_is_2285: 0.014752302162546839
        st_city_id_is_2290: 0.01858119110700504
        st_city_id_is_2295: 0.02200769921943977
        st_city_id_is_2300: 0.05624714279605148
        st_jobs_within_30_min: 0.028914131886565827
        st_ln_empden: 0.0446327890340482
        st_ln_residential_units: 0.07162329038670577
        st_mean_zonal_hhsize: 0.008347264755495756
        st_mode_income_quartile_is_4: 0.06751240691027319
        st_popden: -0.0842537420121421
        st_zone_mean_age_of_head: 0.06005939564394449
        st_zone_prop_race_1: 0.03246711355598011
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07661159664028734
        st_building_age: 0.02580851473464501
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 0.03498148465597544
        st_ln_empden: 0.030788104249445208
        st_ln_residential_units: 0.01024625721186495
        st_mean_zonal_hhsize: 0.026578664500966354
        st_mode_income_quartile_is_4: 0.02586518455212783
        st_popden: 0.029938273865681042
        st_zone_mean_age_of_head: 0.027841823679758924
        st_zone_prop_race_1: 0.04187208658164103
    T-Score:
        st_b_ln_sqft_per_unit: 9.97565582105304
        st_building_age: -5.540112354353135
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 2.7981621685790987
        st_ln_empden: 2.8500831934270474
        st_ln_residential_units: 30.883608189292488
        st_mean_zonal_hhsize: 0.5587478553005374
        st_mode_income_quartile_is_4: 11.667389515120206
        st_popden: -0.04135187228553817
        st_zone_mean_age_of_head: -11.21334544335082
        st_zone_prop_race_1: 10.800701842469207

probability_mode: single_chooser

log_likelihoods:
    convergence: -13147.328941924185
    'null': -13815.510557964428
    ratio: 0.048364598125911984
