name: hlcm100005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 10

choosers_predict_filters: hh_type_large_area_id == 100005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.011028839395391402
        st_building_age: 0.01105714114193905
        st_city_id_is_501: 0.017608892755701388
        st_city_id_is_502: 0.03664045170289504
        st_city_id_is_503: 0.04173050362456399
        st_city_id_is_504: 0.0248323529418832
        st_city_id_is_505: 0.0348223215006839
        st_city_id_is_506: 0.02928799613187519
        st_city_id_is_507: 0.03670397296914666
        st_city_id_is_508: 0.016805599926832285
        st_city_id_is_509: 0.025111038245872457
        st_city_id_is_510: 0.01812156647295908
        st_city_id_is_511: 0.04254707201561687
        st_city_id_is_512: 0.06946540971737666
        st_city_id_is_513: -0.0027247473708330128
        st_city_id_is_514: 0.0051667830562845424
        st_city_id_is_515: 0.040803094924872586
        st_city_id_is_516: 0.025505650117533217
        st_city_id_is_517: 0.023360542975378557
        st_city_id_is_518: -0.005386875508231965
        st_city_id_is_519: 0.03775723095462543
        st_city_id_is_520: 0.052015456553627076
        st_city_id_is_521: 0.006883919085629542
        st_city_id_is_522: 0.02394376818493986
        st_city_id_is_523: 0.040374878854935875
        st_city_id_is_524: -0.04972647109645424
        st_city_id_is_525: -0.006511893979058302
        st_city_id_is_526: 0.04379217679097449
        st_city_id_is_527: 0.04696685962039801
        st_city_id_is_528: 0.03974884504013799
        st_city_id_is_529: -0.006002280213976851
        st_city_id_is_530: 0.003265766086078117
        st_city_id_is_531: 0.06123543660133115
        st_city_id_is_532: 0.01441949265948741
        st_city_id_is_533: -0.12025162993737988
        st_city_id_is_534: -0.0009865575325206815
        st_city_id_is_535: 0.03328781346203716
        st_city_id_is_536: -0.037722863223398774
        st_city_id_is_537: 0.020061722024495635
        st_city_id_is_538: 0.021782645935567065
        st_city_id_is_539: -0.1531156300647001
        st_city_id_is_540: 0.10230090607371
        st_city_id_is_541: 0.05164915796047682
        st_city_id_is_542: 0.00823813873121146
        st_city_id_is_543: 0.06898535618863347
        st_city_id_is_544: -0.006173818082700789
        st_city_id_is_545: 0.09377798523169575
        st_city_id_is_546: 0.04360292658931523
        st_city_id_is_547: 0.021444424644703624
        st_city_id_is_548: -0.0015491651845295385
        st_city_id_is_549: 0.019957446981219196
        st_city_id_is_550: -0.04405563222830087
        st_city_id_is_551: 0.0499324758258123
        st_city_id_is_552: 0.03643810744361238
        st_city_id_is_553: 0.012174731806234068
        st_city_id_is_554: 0.009525525379222086
        st_city_id_is_555: -0.0004877644660847549
        st_jobs_within_30_min: -0.039929960898955195
        st_ln_empden: 0.055623838493457
        st_ln_residential_units: 0.043954587329586355
        st_mean_zonal_hhsize: 0.020477284817831044
        st_mode_income_quartile_is_3: 0.08941183616332567
        st_popden: 0.04369855839146038
        st_zone_mean_age_of_head: -0.043364721849335604
        st_zone_prop_race_1: 0.036125977575794076
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07843481046681368
        st_building_age: 0.028591054700608718
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.040186776004967596
        st_ln_empden: 0.03671281724426314
        st_ln_residential_units: 0.010137876336109828
        st_mean_zonal_hhsize: 0.025492070006356664
        st_mode_income_quartile_is_3: 0.022426365655206358
        st_popden: 0.034315152464508
        st_zone_mean_age_of_head: 0.030864968374234848
        st_zone_prop_race_1: 0.03012395220071166
    T-Score:
        st_b_ln_sqft_per_unit: -3.0806925589137037
        st_building_age: 0.28721059363776247
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: -0.9862695489882896
        st_ln_empden: -0.676628731546073
        st_ln_residential_units: 28.275397546391083
        st_mean_zonal_hhsize: 6.643699451885849
        st_mode_income_quartile_is_3: 6.44905485657916
        st_popden: 3.6312864096221507
        st_zone_mean_age_of_head: 13.62693202517345
        st_zone_prop_race_1: -6.488118576193149

probability_mode: single_chooser

log_likelihoods:
    convergence: -13469.422702974354
    'null': -13815.510557964428
    ratio: 0.025050674279320062
