name: hlcm10005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 1

choosers_predict_filters: hh_type_large_area_id == 10005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_1
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.038191553831363814
        st_building_age: -0.038659198501851684
        st_city_id_is_501: 0.0174117704101649
        st_city_id_is_502: 0.00556864154129554
        st_city_id_is_503: -0.09815517231104548
        st_city_id_is_504: -0.007284249660117302
        st_city_id_is_505: -0.029862169430440733
        st_city_id_is_506: -0.009197820267601508
        st_city_id_is_507: 0.035236922738708557
        st_city_id_is_508: 0.022456230811483464
        st_city_id_is_509: 0.006911020354696748
        st_city_id_is_510: -0.008978020358793734
        st_city_id_is_511: -0.04456916240741532
        st_city_id_is_512: 0.0372516329848403
        st_city_id_is_513: -0.028888057265475012
        st_city_id_is_514: -0.02176297523666615
        st_city_id_is_515: 0.027564705857931644
        st_city_id_is_516: 0.00581558686240463
        st_city_id_is_517: -0.012103956982560369
        st_city_id_is_518: 0.010426894253095714
        st_city_id_is_519: -0.021664043995886367
        st_city_id_is_520: -0.0406665769239754
        st_city_id_is_521: -0.006177915985308663
        st_city_id_is_522: 0.02800681983286875
        st_city_id_is_523: 0.003948937229532485
        st_city_id_is_524: -0.07677688282189216
        st_city_id_is_525: -0.00031586272053025794
        st_city_id_is_526: 0.012534355872033047
        st_city_id_is_527: 0.04131604781288681
        st_city_id_is_528: 0.015509183671947627
        st_city_id_is_529: 0.0014034090182483913
        st_city_id_is_530: -0.0842479781940498
        st_city_id_is_531: 0.018960632763677234
        st_city_id_is_532: 0.041550252879618894
        st_city_id_is_533: -0.03848742372323476
        st_city_id_is_534: -0.021395832245616555
        st_city_id_is_535: 0.00647270371137795
        st_city_id_is_536: 0.035338925773804646
        st_city_id_is_537: -0.006648060027300741
        st_city_id_is_538: 0.021630693688709828
        st_city_id_is_539: -0.050552928808078657
        st_city_id_is_540: 0.06607548672809439
        st_city_id_is_541: -0.10048972232074745
        st_city_id_is_542: -0.018365441783230633
        st_city_id_is_543: 0.04090851460564261
        st_city_id_is_544: -0.028361736903777263
        st_city_id_is_545: 0.017360346840218262
        st_city_id_is_546: 0.009371381751628318
        st_city_id_is_547: -0.007348869689046644
        st_city_id_is_548: 0.00019222413909356496
        st_city_id_is_549: -0.011073226482188116
        st_city_id_is_550: -0.027688547686620674
        st_city_id_is_551: 0.03954937458334394
        st_city_id_is_552: 0.014016349674629272
        st_city_id_is_553: 0.010638078014921759
        st_city_id_is_554: 0.008208341988517876
        st_city_id_is_555: -0.0011217283229060413
        st_jobs_within_30_min: 0.02696040398554868
        st_ln_empden: 0.03237246520475953
        st_ln_residential_units: 0.03429482733646623
        st_mean_zonal_hhsize: -0.039494315322140004
        st_mode_income_quartile_is_1: -0.03237206603900911
        st_popden: 0.028745773676703067
        st_zone_mean_age_of_head: -0.03762278595138038
        st_zone_prop_race_1: 0.0338353688519842
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0934235740553436
        st_building_age: 0.02897509957489094
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.03686856896572102
        st_ln_empden: 0.03136279218256242
        st_ln_residential_units: 0.005972206030878784
        st_mean_zonal_hhsize: 0.02510693013890624
        st_mode_income_quartile_is_1: 0.02732831277674066
        st_popden: 0.027656050415805607
        st_zone_mean_age_of_head: 0.028302881804480214
        st_zone_prop_race_1: 0.03439830347054142
    T-Score:
        st_b_ln_sqft_per_unit: -9.966797421162408
        st_building_age: 0.6825482030978081
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.17424789618236045
        st_ln_empden: -0.5542157439252532
        st_ln_residential_units: 75.21171475743681
        st_mean_zonal_hhsize: -4.235097283984752
        st_mode_income_quartile_is_1: 7.404657364377086
        st_popden: -0.5938747213353917
        st_zone_mean_age_of_head: 13.832729773371288
        st_zone_prop_race_1: 2.336061548797242

probability_mode: single_chooser

log_likelihoods:
    convergence: -11386.358423734533
    'null': -13815.510557964428
    ratio: 0.1758278945999231
