name: hlcm80005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 8

choosers_predict_filters: hh_type_large_area_id == 80005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.026107713967663992
        st_building_age: -0.015796972644496952
        st_city_id_is_501: -0.010619115046904439
        st_city_id_is_502: 0.0733449789629384
        st_city_id_is_503: -0.06814080644048344
        st_city_id_is_504: 0.0018496177424384538
        st_city_id_is_505: 0.00756151086330361
        st_city_id_is_506: -0.06725532966584996
        st_city_id_is_507: 0.03348299953501263
        st_city_id_is_508: 0.04640743325464137
        st_city_id_is_509: -0.0009219365652781179
        st_city_id_is_510: 0.023425252126455517
        st_city_id_is_511: 0.02267226837990227
        st_city_id_is_512: -0.08063180507155432
        st_city_id_is_513: 0.03686217669839401
        st_city_id_is_514: -0.05166385219040745
        st_city_id_is_515: 0.036953867451545226
        st_city_id_is_516: 0.011134511294272693
        st_city_id_is_517: -0.062295577992909364
        st_city_id_is_518: 0.01148560688032902
        st_city_id_is_519: 0.012423558396428419
        st_city_id_is_520: 0.04574967303006041
        st_city_id_is_521: 0.0034493649655695287
        st_city_id_is_522: 0.032021611698555774
        st_city_id_is_523: 0.02161870880187781
        st_city_id_is_524: 0.04473806804944578
        st_city_id_is_525: 0.00137529013297386
        st_city_id_is_526: 0.030752653037777324
        st_city_id_is_527: 0.045043495042820285
        st_city_id_is_528: 0.030005201969347875
        st_city_id_is_529: 0.016020753671365545
        st_city_id_is_530: 0.004766865303185338
        st_city_id_is_531: 0.0386413056514926
        st_city_id_is_532: 0.04818413587287221
        st_city_id_is_533: -0.01922985343848132
        st_city_id_is_534: 0.0008888974000964206
        st_city_id_is_535: 0.0308135279214037
        st_city_id_is_536: 0.004653540208056757
        st_city_id_is_537: -0.008497764715779383
        st_city_id_is_538: 0.03057533661714448
        st_city_id_is_539: -0.013389679591028119
        st_city_id_is_540: 0.08462802910269988
        st_city_id_is_541: 0.07338240069360692
        st_city_id_is_542: 0.03825122624958499
        st_city_id_is_543: 0.04731995697891597
        st_city_id_is_544: -0.038697977454792365
        st_city_id_is_545: 0.05800635232640144
        st_city_id_is_546: 0.029269775901881883
        st_city_id_is_547: 0.010412849754297172
        st_city_id_is_548: 0.009889488011248013
        st_city_id_is_549: -0.016894658297501385
        st_city_id_is_550: -0.03436632894779566
        st_city_id_is_551: 0.01625988163514639
        st_city_id_is_552: 0.0037767685419023097
        st_city_id_is_553: 0.008313670196991332
        st_city_id_is_554: 0.018885366977768867
        st_city_id_is_555: -0.0002450004215806261
        st_jobs_within_30_min: 0.0623690123332292
        st_ln_empden: 0.045880184407187045
        st_ln_residential_units: 0.034678427023967735
        st_mean_zonal_hhsize: -0.041724742971533495
        st_mode_income_quartile_is_3: 0.04376771184036525
        st_popden: 0.04428502152563114
        st_zone_mean_age_of_head: -0.037235419992851494
        st_zone_prop_race_1: 0.044181389609665354
    Std. Error:
        st_b_ln_sqft_per_unit: 0.08342905434413869
        st_building_age: 0.027040874284207175
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.03646406738284416
        st_ln_empden: 0.029427951277893313
        st_ln_residential_units: 0.007875989133136857
        st_mean_zonal_hhsize: 0.026798765296899264
        st_mode_income_quartile_is_3: 0.021999081666605514
        st_popden: 0.03235263301818735
        st_zone_mean_age_of_head: 0.02651198960801726
        st_zone_prop_race_1: 0.033128105368791946
    T-Score:
        st_b_ln_sqft_per_unit: -5.522179870352039
        st_building_age: -0.23418325432411005
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 1.610853383429332
        st_ln_empden: -1.1876096473504485
        st_ln_residential_units: 46.8162176342789
        st_mean_zonal_hhsize: -7.283129038883423
        st_mode_income_quartile_is_3: 3.004775332363557
        st_popden: -2.019333298154038
        st_zone_mean_age_of_head: -3.113285134439511
        st_zone_prop_race_1: 5.174757844369395

probability_mode: single_chooser

log_likelihoods:
    convergence: -12818.53324997757
    'null': -13815.510557964428
    ratio: 0.07216362390690767
