name: hlcm20003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 2

choosers_predict_filters: hh_type_large_area_id == 20003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_1
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.04733869948299249
        st_building_age: 0.04495598071503229
        st_city_id_is_1005: -0.03051537654213693
        st_city_id_is_1010: 0.007466568347424583
        st_city_id_is_1015: 0.05416766761306142
        st_city_id_is_1020: -0.04543999939765415
        st_city_id_is_1025: 0.014832907003418251
        st_city_id_is_1030: 0.028138823524768434
        st_city_id_is_1040: 0.004007195313297879
        st_city_id_is_1045: 0.043267499058741714
        st_city_id_is_1050: 0.019624258726711575
        st_city_id_is_1055: 0.024772210275853395
        st_city_id_is_1060: 0.021248717412911615
        st_city_id_is_1065: 0.021491034221383615
        st_city_id_is_1070: -0.0010527444160429974
        st_city_id_is_1075: 0.0021605412337702976
        st_city_id_is_1080: 0.027505357704454614
        st_city_id_is_1085: -0.03223869918758296
        st_city_id_is_1090: -0.0427745274680004
        st_city_id_is_1095: 0.006362632452358871
        st_city_id_is_1100: 0.048047491260356075
        st_city_id_is_1105: 0.03459830610348243
        st_city_id_is_1110: 0.0181687194632558
        st_city_id_is_1115: 0.006068833899168737
        st_city_id_is_1120: 0.027612896373320456
        st_city_id_is_1125: 0.036445989917003783
        st_city_id_is_1130: 0.019433346386303497
        st_city_id_is_1135: -0.04256630959876025
        st_city_id_is_1140: 0.0005921501799797805
        st_city_id_is_1145: -0.03426387978070503
        st_city_id_is_1150: 0.02852875473678934
        st_city_id_is_1155: -0.14162364774328806
        st_city_id_is_1160: 0.06059629980954957
        st_city_id_is_1165: 0.018433285501694326
        st_city_id_is_1170: 0.02256860422249234
        st_city_id_is_1175: 0.06945328664974891
        st_city_id_is_1180: 0.007696824269015698
        st_city_id_is_1185: 0.06068290152180999
        st_city_id_is_1190: 0.03205489410565986
        st_city_id_is_1200: 0.0070965455481236325
        st_city_id_is_1205: 0.05255938789563135
        st_city_id_is_1210: 0.060559292195632136
        st_city_id_is_1215: 0.05084085328711148
        st_city_id_is_1220: 0.010556138043660459
        st_jobs_within_30_min: 0.04294557781099684
        st_ln_empden: 0.043184063983245646
        st_ln_residential_units: -0.01877027707699175
        st_mean_zonal_hhsize: -0.05616517877966552
        st_mode_income_quartile_is_1: 0.041477837847607994
        st_popden: 0.039702589378973835
        st_zone_mean_age_of_head: 0.04892092126939749
        st_zone_prop_race_1: 0.04353587021050035
    Std. Error:
        st_b_ln_sqft_per_unit: 0.09652975139963209
        st_building_age: 0.02718409731213641
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03533537275267524
        st_ln_empden: 0.028895156306026393
        st_ln_residential_units: 0.0064407376101322964
        st_mean_zonal_hhsize: 0.025253925396126305
        st_mode_income_quartile_is_1: 0.026674489138600082
        st_popden: 0.022770543534857166
        st_zone_mean_age_of_head: 0.026520887126616956
        st_zone_prop_race_1: 0.03236856976391456
    T-Score:
        st_b_ln_sqft_per_unit: -14.34063732419352
        st_building_age: 2.2095593589602256
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: -1.8726769491096764
        st_ln_empden: -0.048843353510058925
        st_ln_residential_units: 64.97492072668696
        st_mean_zonal_hhsize: -4.415417941664101
        st_mode_income_quartile_is_1: 7.402953876612925
        st_popden: -0.9348877160919243
        st_zone_mean_age_of_head: 0.9509962575588654
        st_zone_prop_race_1: -4.368260772867309

probability_mode: single_chooser

log_likelihoods:
    convergence: -11606.288621353506
    'null': -13815.510557964428
    ratio: 0.15990881606162144
