name: hlcm110005

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 11

choosers_predict_filters: hh_type_large_area_id == 110005

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_501
- st_city_id_is_502
- st_city_id_is_503
- st_city_id_is_504
- st_city_id_is_505
- st_city_id_is_506
- st_city_id_is_507
- st_city_id_is_508
- st_city_id_is_509
- st_city_id_is_510
- st_city_id_is_511
- st_city_id_is_512
- st_city_id_is_513
- st_city_id_is_514
- st_city_id_is_515
- st_city_id_is_516
- st_city_id_is_517
- st_city_id_is_518
- st_city_id_is_519
- st_city_id_is_520
- st_city_id_is_521
- st_city_id_is_522
- st_city_id_is_523
- st_city_id_is_524
- st_city_id_is_525
- st_city_id_is_526
- st_city_id_is_527
- st_city_id_is_528
- st_city_id_is_529
- st_city_id_is_530
- st_city_id_is_531
- st_city_id_is_532
- st_city_id_is_533
- st_city_id_is_534
- st_city_id_is_535
- st_city_id_is_536
- st_city_id_is_537
- st_city_id_is_538
- st_city_id_is_539
- st_city_id_is_540
- st_city_id_is_541
- st_city_id_is_542
- st_city_id_is_543
- st_city_id_is_544
- st_city_id_is_545
- st_city_id_is_546
- st_city_id_is_547
- st_city_id_is_548
- st_city_id_is_549
- st_city_id_is_550
- st_city_id_is_551
- st_city_id_is_552
- st_city_id_is_553
- st_city_id_is_554
- st_city_id_is_555
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.050996947181660125
        st_building_age: 0.06855089704972206
        st_city_id_is_501: 0.032032819011831276
        st_city_id_is_502: 0.09393757444215987
        st_city_id_is_503: 0.027835362524250173
        st_city_id_is_504: 0.007120383965056609
        st_city_id_is_505: 0.005478560735731739
        st_city_id_is_506: 0.029210560779444845
        st_city_id_is_507: 0.043508056262955924
        st_city_id_is_508: 0.02957637468776462
        st_city_id_is_509: 0.05575914916841032
        st_city_id_is_510: 0.008203786785313357
        st_city_id_is_511: 0.03433189283190358
        st_city_id_is_512: 0.017106214676834812
        st_city_id_is_513: 0.03223461470883553
        st_city_id_is_514: -0.0076190394737990965
        st_city_id_is_515: 0.03253865915541849
        st_city_id_is_516: -0.03694307363478458
        st_city_id_is_517: 0.03397062486740624
        st_city_id_is_518: 0.01391222913593435
        st_city_id_is_519: 0.026083267021001184
        st_city_id_is_520: 0.06892394618626783
        st_city_id_is_521: -0.07897616764575013
        st_city_id_is_522: 0.020196796874765697
        st_city_id_is_523: 0.008546422153886785
        st_city_id_is_524: 0.06477093193027171
        st_city_id_is_525: 0.04664998180610705
        st_city_id_is_526: 0.035697475265690594
        st_city_id_is_527: 0.04549063698881672
        st_city_id_is_528: 0.02664892176446141
        st_city_id_is_529: -0.037716144562741326
        st_city_id_is_530: 0.006660617786095692
        st_city_id_is_531: 0.06298668272380703
        st_city_id_is_532: 0.04182145238639732
        st_city_id_is_533: -0.0006994912391948395
        st_city_id_is_534: 0.022293595939986026
        st_city_id_is_535: 0.03748988511224296
        st_city_id_is_536: -0.08512136441331308
        st_city_id_is_537: 0.03134074924112078
        st_city_id_is_538: 0.023218237340059768
        st_city_id_is_539: -0.008741916507917408
        st_city_id_is_540: 0.09922485332642135
        st_city_id_is_541: 0.0798594374819902
        st_city_id_is_542: -0.0005938244560010199
        st_city_id_is_543: 0.0570161155138424
        st_city_id_is_544: -0.02963106676487945
        st_city_id_is_545: 0.0755592910245516
        st_city_id_is_546: -0.1635724526328036
        st_city_id_is_547: 0.03164343976227239
        st_city_id_is_548: 0.0237272010337584
        st_city_id_is_549: 0.017501387313297083
        st_city_id_is_550: -0.0012133535616626685
        st_city_id_is_551: 0.049512889123786284
        st_city_id_is_552: 0.03780966920269381
        st_city_id_is_553: 0.0207289755404623
        st_city_id_is_554: 0.015009250509398097
        st_city_id_is_555: -0.0010390868637405698
        st_jobs_within_30_min: -0.012000773690761635
        st_ln_empden: 0.044893855259814174
        st_ln_residential_units: 0.042477580984175145
        st_mean_zonal_hhsize: 0.03669008540173876
        st_mode_income_quartile_is_3: 0.0675540472028941
        st_popden: 0.05972221126502166
        st_zone_mean_age_of_head: 0.018521016229675186
        st_zone_prop_race_1: -0.0009669954306066634
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07776119132367144
        st_building_age: 0.026298065208424117
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: 0.03718336046276335
        st_ln_empden: 0.032835385329456346
        st_ln_residential_units: 0.010379679470397767
        st_mean_zonal_hhsize: 0.025364272640120814
        st_mode_income_quartile_is_3: 0.021780486523407975
        st_popden: 0.033445203511581374
        st_zone_mean_age_of_head: 0.030349654933584103
        st_zone_prop_race_1: 0.03178517432754698
    T-Score:
        st_b_ln_sqft_per_unit: -6.137003592381195
        st_building_age: -1.5172157707663185
        st_city_id_is_501: 0.0
        st_city_id_is_502: 0.0
        st_city_id_is_503: 0.0
        st_city_id_is_504: 0.0
        st_city_id_is_505: 0.0
        st_city_id_is_506: 0.0
        st_city_id_is_507: 0.0
        st_city_id_is_508: 0.0
        st_city_id_is_509: 0.0
        st_city_id_is_510: 0.0
        st_city_id_is_511: 0.0
        st_city_id_is_512: 0.0
        st_city_id_is_513: 0.0
        st_city_id_is_514: 0.0
        st_city_id_is_515: 0.0
        st_city_id_is_516: 0.0
        st_city_id_is_517: 0.0
        st_city_id_is_518: 0.0
        st_city_id_is_519: 0.0
        st_city_id_is_520: 0.0
        st_city_id_is_521: 0.0
        st_city_id_is_522: 0.0
        st_city_id_is_523: 0.0
        st_city_id_is_524: 0.0
        st_city_id_is_525: 0.0
        st_city_id_is_526: 0.0
        st_city_id_is_527: 0.0
        st_city_id_is_528: 0.0
        st_city_id_is_529: 0.0
        st_city_id_is_530: 0.0
        st_city_id_is_531: 0.0
        st_city_id_is_532: 0.0
        st_city_id_is_533: 0.0
        st_city_id_is_534: 0.0
        st_city_id_is_535: 0.0
        st_city_id_is_536: 0.0
        st_city_id_is_537: 0.0
        st_city_id_is_538: 0.0
        st_city_id_is_539: 0.0
        st_city_id_is_540: 0.0
        st_city_id_is_541: 0.0
        st_city_id_is_542: 0.0
        st_city_id_is_543: 0.0
        st_city_id_is_544: 0.0
        st_city_id_is_545: 0.0
        st_city_id_is_546: 0.0
        st_city_id_is_547: 0.0
        st_city_id_is_548: 0.0
        st_city_id_is_549: 0.0
        st_city_id_is_550: 0.0
        st_city_id_is_551: 0.0
        st_city_id_is_552: 0.0
        st_city_id_is_553: 0.0
        st_city_id_is_554: 0.0
        st_city_id_is_555: 0.0
        st_jobs_within_30_min: -0.08058374305500794
        st_ln_empden: -0.1733045809237324
        st_ln_residential_units: 27.198605581846977
        st_mean_zonal_hhsize: 4.807553631502464
        st_mode_income_quartile_is_3: 5.047423649007951
        st_popden: 0.8828826695299985
        st_zone_mean_age_of_head: -1.0821681991796808
        st_zone_prop_race_1: 2.0847263096799846

probability_mode: single_chooser

log_likelihoods:
    convergence: -13554.083459644558
    'null': -13815.510557964428
    ratio: 0.018922724370049493
