name: hlcm170003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 17

choosers_predict_filters: hh_type_large_area_id == 170003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.05256152048390228
        st_building_age: -0.05091706073116459
        st_city_id_is_1005: 0.035943503551550876
        st_city_id_is_1010: 0.03931712910210486
        st_city_id_is_1015: -0.030378535444221557
        st_city_id_is_1020: 0.04878113978887191
        st_city_id_is_1025: 0.04863990756246428
        st_city_id_is_1030: 0.05313199086515668
        st_city_id_is_1040: 0.018253625038288725
        st_city_id_is_1045: 0.04121976873478162
        st_city_id_is_1050: 0.008960810482147101
        st_city_id_is_1055: 0.03864491703791729
        st_city_id_is_1060: -0.0007923931012467878
        st_city_id_is_1065: 0.06822742156680463
        st_city_id_is_1070: 0.028994338538528636
        st_city_id_is_1075: 0.04026502611356963
        st_city_id_is_1080: 0.060081734670047494
        st_city_id_is_1085: -0.1551878593400023
        st_city_id_is_1090: 0.006934087785654336
        st_city_id_is_1095: 0.005361277220449366
        st_city_id_is_1100: 0.01668034698457227
        st_city_id_is_1105: 0.06767767121984819
        st_city_id_is_1110: -0.03799686016164331
        st_city_id_is_1115: -0.0401090985392975
        st_city_id_is_1120: -0.03302315561393092
        st_city_id_is_1125: 0.024934488405947287
        st_city_id_is_1130: 0.04310928901867393
        st_city_id_is_1135: 0.027310168369659136
        st_city_id_is_1140: 0.06612709028261603
        st_city_id_is_1145: -0.005366877916289723
        st_city_id_is_1150: -0.05864484387331733
        st_city_id_is_1155: -0.006191749734183988
        st_city_id_is_1160: 0.03852782131562789
        st_city_id_is_1165: 0.048887279975292186
        st_city_id_is_1170: -0.011498977237630157
        st_city_id_is_1175: 0.009554686735607103
        st_city_id_is_1180: 0.004193810773228993
        st_city_id_is_1185: -0.11589058203651571
        st_city_id_is_1190: 0.06136690126495889
        st_city_id_is_1200: 0.012152365309128419
        st_city_id_is_1205: 0.014235185819464312
        st_city_id_is_1210: 0.05626042661951739
        st_city_id_is_1215: 0.07443287840132864
        st_city_id_is_1220: 0.026616569897140795
        st_jobs_within_30_min: -0.0457904984025742
        st_ln_empden: -0.04430420257922848
        st_ln_residential_units: 0.04082310189062737
        st_mean_zonal_hhsize: 0.051030932234913826
        st_mode_income_quartile_is_4: 0.05416996091151625
        st_popden: -0.03419929588195466
        st_zone_mean_age_of_head: -0.04385948401401463
        st_zone_prop_race_1: 0.052220273739033464
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07470981480143236
        st_building_age: 0.026832803860462568
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03896712170156199
        st_ln_empden: 0.03290092119038443
        st_ln_residential_units: 0.015117441186768566
        st_mean_zonal_hhsize: 0.026760361427924376
        st_mode_income_quartile_is_4: 0.02639271800389025
        st_popden: 0.0324708336006058
        st_zone_mean_age_of_head: 0.033340275190088815
        st_zone_prop_race_1: 0.04345819948641526
    T-Score:
        st_b_ln_sqft_per_unit: 15.047422312801482
        st_building_age: -7.488973740140894
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.04071757040263062
        st_ln_empden: 3.081492469090734
        st_ln_residential_units: 15.37763449655542
        st_mean_zonal_hhsize: 3.024376348929615
        st_mode_income_quartile_is_4: 11.129821342800984
        st_popden: -0.21505606360626583
        st_zone_mean_age_of_head: -0.581964291045879
        st_zone_prop_race_1: 6.128213286064595

probability_mode: single_chooser

log_likelihoods:
    convergence: -13269.335396249911
    'null': -13815.510557964428
    ratio: 0.039533476480871355
