name: hlcm60003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 6

choosers_predict_filters: hh_type_large_area_id == 60003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_1
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.11131363778379118
        st_building_age: 0.1087914270304905
        st_city_id_is_1005: -0.037415097451204166
        st_city_id_is_1010: -0.0078100586563704015
        st_city_id_is_1015: 0.03062595736133781
        st_city_id_is_1020: -0.09641143934613489
        st_city_id_is_1025: 0.11136299266244756
        st_city_id_is_1030: 0.09192712971248758
        st_city_id_is_1040: 0.016172549832154808
        st_city_id_is_1045: 0.003975669688470927
        st_city_id_is_1050: -0.005249246498716627
        st_city_id_is_1055: 0.018210727200175976
        st_city_id_is_1060: -0.10886808204331923
        st_city_id_is_1065: -0.03886291810441546
        st_city_id_is_1070: -0.018018020718794967
        st_city_id_is_1075: -0.01364594530680481
        st_city_id_is_1080: -0.02626343886020563
        st_city_id_is_1085: -0.03596085315562594
        st_city_id_is_1090: 0.048147202000953356
        st_city_id_is_1095: 0.004990446845495544
        st_city_id_is_1100: 0.012865187848889664
        st_city_id_is_1105: 0.04854856091251376
        st_city_id_is_1110: 0.06779287360786035
        st_city_id_is_1115: 0.026227989094558493
        st_city_id_is_1120: -0.19017429784152562
        st_city_id_is_1125: -0.00038893608806355275
        st_city_id_is_1130: -0.05423522161536283
        st_city_id_is_1135: -0.14063171368610286
        st_city_id_is_1140: 0.009497999028362814
        st_city_id_is_1145: -0.13082932712233475
        st_city_id_is_1150: 0.022875232190543982
        st_city_id_is_1155: 0.030494739045487756
        st_city_id_is_1160: 0.02080431438466393
        st_city_id_is_1165: -0.0790178821987068
        st_city_id_is_1170: 0.05208225503638214
        st_city_id_is_1175: 0.04455464534452953
        st_city_id_is_1180: 0.005536464585584175
        st_city_id_is_1185: 0.12577247494859695
        st_city_id_is_1190: 0.024123534143610837
        st_city_id_is_1200: -0.02554604391639915
        st_city_id_is_1205: 0.022206380986142044
        st_city_id_is_1210: 0.08217643700288148
        st_city_id_is_1215: 0.06637944004625979
        st_city_id_is_1220: -0.0068244540822007095
        st_jobs_within_30_min: 0.08021903006813079
        st_ln_empden: 0.09950523458409188
        st_ln_residential_units: -0.11252757586105881
        st_mean_zonal_hhsize: 0.06551948789415145
        st_mode_income_quartile_is_1: 0.10005955912939597
        st_popden: 0.09289438868901478
        st_zone_mean_age_of_head: 0.025686264096739318
        st_zone_prop_race_1: 0.001394454183752776
    Std. Error:
        st_b_ln_sqft_per_unit: 0.10481952900960546
        st_building_age: 0.026371021893426622
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.0348160555387689
        st_ln_empden: 0.03147694689652615
        st_ln_residential_units: 0.007146291617270865
        st_mean_zonal_hhsize: 0.02098816541320307
        st_mode_income_quartile_is_1: 0.027014110182344633
        st_popden: 0.01954477953176209
        st_zone_mean_age_of_head: 0.0233507138588899
        st_zone_prop_race_1: 0.030431862227965442
    T-Score:
        st_b_ln_sqft_per_unit: -10.920984992989164
        st_building_age: 0.7604445560286449
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.5726029741564834
        st_ln_empden: -1.8732128783582382
        st_ln_residential_units: 53.91014668404615
        st_mean_zonal_hhsize: 9.40503471191915
        st_mode_income_quartile_is_1: 15.603246847484385
        st_popden: 0.16043748185960754
        st_zone_mean_age_of_head: -14.612740118849246
        st_zone_prop_race_1: -4.029920115644981

probability_mode: single_chooser

log_likelihoods:
    convergence: -11710.111663988753
    'null': -13815.510557964428
    ratio: 0.15239385364313918
