name: hlcm80125

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 8

choosers_predict_filters: hh_type_large_area_id == 80125

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_2005
- st_city_id_is_2010
- st_city_id_is_2015
- st_city_id_is_2020
- st_city_id_is_2025
- st_city_id_is_2030
- st_city_id_is_2035
- st_city_id_is_2040
- st_city_id_is_2045
- st_city_id_is_2050
- st_city_id_is_2055
- st_city_id_is_2060
- st_city_id_is_2065
- st_city_id_is_2072
- st_city_id_is_2075
- st_city_id_is_2080
- st_city_id_is_2085
- st_city_id_is_2090
- st_city_id_is_2095
- st_city_id_is_2100
- st_city_id_is_2105
- st_city_id_is_2110
- st_city_id_is_2115
- st_city_id_is_2120
- st_city_id_is_2125
- st_city_id_is_2130
- st_city_id_is_2135
- st_city_id_is_2140
- st_city_id_is_2145
- st_city_id_is_2150
- st_city_id_is_2155
- st_city_id_is_2160
- st_city_id_is_2165
- st_city_id_is_2170
- st_city_id_is_2175
- st_city_id_is_2180
- st_city_id_is_2185
- st_city_id_is_2190
- st_city_id_is_2195
- st_city_id_is_2200
- st_city_id_is_2205
- st_city_id_is_2210
- st_city_id_is_2215
- st_city_id_is_2220
- st_city_id_is_2230
- st_city_id_is_2235
- st_city_id_is_2240
- st_city_id_is_2245
- st_city_id_is_2250
- st_city_id_is_2255
- st_city_id_is_2260
- st_city_id_is_2265
- st_city_id_is_2270
- st_city_id_is_2275
- st_city_id_is_2280
- st_city_id_is_2285
- st_city_id_is_2290
- st_city_id_is_2295
- st_city_id_is_2300
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.012536040103763869
        st_building_age: 0.02390682456578919
        st_city_id_is_2005: -0.004379611563396936
        st_city_id_is_2010: 0.03333725525404739
        st_city_id_is_2015: -0.0370670355331333
        st_city_id_is_2020: 0.004210962900247252
        st_city_id_is_2025: 0.0071382672812966425
        st_city_id_is_2030: -0.021754398204747682
        st_city_id_is_2035: -0.02523871135514538
        st_city_id_is_2040: 0.03024374047509745
        st_city_id_is_2045: -0.032179723858400316
        st_city_id_is_2050: 0.018590683704796194
        st_city_id_is_2055: -0.040189001439865785
        st_city_id_is_2060: -0.016216554139380352
        st_city_id_is_2065: 0.038951725935890774
        st_city_id_is_2072: 0.09887040937935962
        st_city_id_is_2075: 0.03592174805048266
        st_city_id_is_2080: 0.023847221722804512
        st_city_id_is_2085: 0.010096046081727683
        st_city_id_is_2090: -0.19773950922945363
        st_city_id_is_2095: -0.05287711523642181
        st_city_id_is_2100: -0.056907262970034275
        st_city_id_is_2105: 0.006554699211756907
        st_city_id_is_2110: 0.010239793478702588
        st_city_id_is_2115: -0.05692259962999771
        st_city_id_is_2120: -0.0037683092085937808
        st_city_id_is_2125: 0.02816085183775915
        st_city_id_is_2130: 0.006402173877012229
        st_city_id_is_2135: -0.027287868512834178
        st_city_id_is_2140: 0.009351345175187901
        st_city_id_is_2145: -0.06644056918985282
        st_city_id_is_2150: 0.06632513544642028
        st_city_id_is_2155: 0.017220614179506297
        st_city_id_is_2160: -0.041934738001704254
        st_city_id_is_2165: -0.013830775441590204
        st_city_id_is_2170: 0.053609456025010084
        st_city_id_is_2175: -0.030797057779330513
        st_city_id_is_2180: 0.021886279072299716
        st_city_id_is_2185: -0.0005167389130008254
        st_city_id_is_2190: 0.00888651298749747
        st_city_id_is_2195: 0.02092080032787012
        st_city_id_is_2200: -0.08628838099206217
        st_city_id_is_2205: -0.0016345840486203984
        st_city_id_is_2210: -0.013008562494993308
        st_city_id_is_2215: -0.0880754446207489
        st_city_id_is_2220: 0.0045388152786925585
        st_city_id_is_2230: 0.06097041603864643
        st_city_id_is_2235: -0.006488303638760746
        st_city_id_is_2240: 0.0428256168531982
        st_city_id_is_2245: 0.009585178254898418
        st_city_id_is_2250: 0.0318338080682234
        st_city_id_is_2255: -0.024566484049260092
        st_city_id_is_2260: 0.02074354248005698
        st_city_id_is_2265: -0.03408125740428617
        st_city_id_is_2270: 0.07614651214388776
        st_city_id_is_2275: -0.027922461172672563
        st_city_id_is_2280: 0.022887961179681116
        st_city_id_is_2285: -0.0028123655290733054
        st_city_id_is_2290: 0.07034844887060354
        st_city_id_is_2295: 0.020265716422053957
        st_city_id_is_2300: 0.013704686338824424
        st_jobs_within_30_min: 0.05333593177437302
        st_ln_empden: 0.05368063872411681
        st_ln_residential_units: 0.0587784210629683
        st_mean_zonal_hhsize: -0.04550268957409551
        st_mode_income_quartile_is_3: 0.04544729381735912
        st_popden: 0.03944297420949923
        st_zone_mean_age_of_head: 0.10494920654182714
        st_zone_prop_race_1: 0.04424391840155536
    Std. Error:
        st_b_ln_sqft_per_unit: 0.08342905434413869
        st_building_age: 0.027040874284207175
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 0.03646406738284416
        st_ln_empden: 0.029427951277893313
        st_ln_residential_units: 0.007875989133136857
        st_mean_zonal_hhsize: 0.026798765296899264
        st_mode_income_quartile_is_3: 0.021999081666605514
        st_popden: 0.03235263301818735
        st_zone_mean_age_of_head: 0.02651198960801726
        st_zone_prop_race_1: 0.033128105368791946
    T-Score:
        st_b_ln_sqft_per_unit: -5.522179870352039
        st_building_age: -0.23418325432411005
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 1.610853383429332
        st_ln_empden: -1.1876096473504485
        st_ln_residential_units: 46.8162176342789
        st_mean_zonal_hhsize: -7.283129038883423
        st_mode_income_quartile_is_3: 3.004775332363557
        st_popden: -2.019333298154038
        st_zone_mean_age_of_head: -3.113285134439511
        st_zone_prop_race_1: 5.174757844369395

probability_mode: single_chooser

log_likelihoods:
    convergence: -12818.53324997757
    'null': -13815.510557964428
    ratio: 0.07216362390690767
