name: hlcm110003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 11

choosers_predict_filters: hh_type_large_area_id == 110003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_3
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: -0.03909777573447488
        st_building_age: 0.04498839148762207
        st_city_id_is_1005: -0.012180898783775308
        st_city_id_is_1010: -0.009430456768305676
        st_city_id_is_1015: 0.0063940926852872676
        st_city_id_is_1020: -0.03222029112984439
        st_city_id_is_1025: 0.06491703735104272
        st_city_id_is_1030: -0.007727653052884559
        st_city_id_is_1040: -0.019148155100453836
        st_city_id_is_1045: 0.0037419307428987534
        st_city_id_is_1050: 0.012085497368074892
        st_city_id_is_1055: 0.02805527981988124
        st_city_id_is_1060: 0.006083214552597272
        st_city_id_is_1065: -0.023645707982083698
        st_city_id_is_1070: -0.022232407994029427
        st_city_id_is_1075: -0.010120135535939519
        st_city_id_is_1080: 0.0006343720020329891
        st_city_id_is_1085: -0.01994828258507557
        st_city_id_is_1090: -0.028140295046526136
        st_city_id_is_1095: -0.02655919922236974
        st_city_id_is_1100: 0.007252423051695898
        st_city_id_is_1105: 0.01949492869568348
        st_city_id_is_1110: -0.017496920568263977
        st_city_id_is_1115: 0.0009534466239306551
        st_city_id_is_1120: -0.0035231306907516275
        st_city_id_is_1125: 0.024934342618948304
        st_city_id_is_1130: -0.0108616160877084
        st_city_id_is_1135: -0.057866143173748524
        st_city_id_is_1140: -0.009696377748930037
        st_city_id_is_1145: -0.04954007890550731
        st_city_id_is_1150: -0.016360455499713964
        st_city_id_is_1155: -0.136061107421937
        st_city_id_is_1160: 0.03162303537596389
        st_city_id_is_1165: 0.028660435789299398
        st_city_id_is_1170: 0.005735598885497237
        st_city_id_is_1175: 0.02283553977484558
        st_city_id_is_1180: -0.020859942828347078
        st_city_id_is_1185: -0.004796585635627463
        st_city_id_is_1190: 0.011225367823043262
        st_city_id_is_1200: 0.003237587878709837
        st_city_id_is_1205: 0.002921558656360633
        st_city_id_is_1210: 0.038913172103762834
        st_city_id_is_1215: 0.05778932164960124
        st_city_id_is_1220: -0.014531490419050004
        st_jobs_within_30_min: 0.0525003413108481
        st_ln_empden: 0.04695333233159461
        st_ln_residential_units: -0.030580034323629976
        st_mean_zonal_hhsize: 0.017966575820878412
        st_mode_income_quartile_is_3: 0.04221384454981844
        st_popden: 0.04552209020354898
        st_zone_mean_age_of_head: 0.013385580871420442
        st_zone_prop_race_1: 0.047428098175633114
    Std. Error:
        st_b_ln_sqft_per_unit: 0.07776119132367144
        st_building_age: 0.026298065208424117
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.03718336046276335
        st_ln_empden: 0.032835385329456346
        st_ln_residential_units: 0.010379679470397767
        st_mean_zonal_hhsize: 0.025364272640120814
        st_mode_income_quartile_is_3: 0.021780486523407975
        st_popden: 0.033445203511581374
        st_zone_mean_age_of_head: 0.030349654933584103
        st_zone_prop_race_1: 0.03178517432754698
    T-Score:
        st_b_ln_sqft_per_unit: -6.137003592381195
        st_building_age: -1.5172157707663185
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: -0.08058374305500794
        st_ln_empden: -0.1733045809237324
        st_ln_residential_units: 27.198605581846977
        st_mean_zonal_hhsize: 4.807553631502464
        st_mode_income_quartile_is_3: 5.047423649007951
        st_popden: 0.8828826695299985
        st_zone_mean_age_of_head: -1.0821681991796808
        st_zone_prop_race_1: 2.0847263096799846

probability_mode: single_chooser

log_likelihoods:
    convergence: -13554.083459644558
    'null': -13815.510557964428
    ratio: 0.018922724370049493
