name: hlcm150003

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 15

choosers_predict_filters: hh_type_large_area_id == 150003

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_1005
- st_city_id_is_1010
- st_city_id_is_1015
- st_city_id_is_1020
- st_city_id_is_1025
- st_city_id_is_1030
- st_city_id_is_1040
- st_city_id_is_1045
- st_city_id_is_1050
- st_city_id_is_1055
- st_city_id_is_1060
- st_city_id_is_1065
- st_city_id_is_1070
- st_city_id_is_1075
- st_city_id_is_1080
- st_city_id_is_1085
- st_city_id_is_1090
- st_city_id_is_1095
- st_city_id_is_1100
- st_city_id_is_1105
- st_city_id_is_1110
- st_city_id_is_1115
- st_city_id_is_1120
- st_city_id_is_1125
- st_city_id_is_1130
- st_city_id_is_1135
- st_city_id_is_1140
- st_city_id_is_1145
- st_city_id_is_1150
- st_city_id_is_1155
- st_city_id_is_1160
- st_city_id_is_1165
- st_city_id_is_1170
- st_city_id_is_1175
- st_city_id_is_1180
- st_city_id_is_1185
- st_city_id_is_1190
- st_city_id_is_1200
- st_city_id_is_1205
- st_city_id_is_1210
- st_city_id_is_1215
- st_city_id_is_1220
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.07519570355544372
        st_building_age: -0.06419082979415502
        st_city_id_is_1005: 0.07334072619632945
        st_city_id_is_1010: -0.02385031566397382
        st_city_id_is_1015: 0.07265242661971573
        st_city_id_is_1020: 0.06566155525507164
        st_city_id_is_1025: 0.04931889757090549
        st_city_id_is_1030: -0.10016316549495329
        st_city_id_is_1040: -0.030211342186019494
        st_city_id_is_1045: 0.02235848226631631
        st_city_id_is_1050: 0.012169314246614871
        st_city_id_is_1055: 0.006884364645513749
        st_city_id_is_1060: 0.07128551873466897
        st_city_id_is_1065: 0.08033680411772665
        st_city_id_is_1070: 0.0911610764340221
        st_city_id_is_1075: 0.08697010158581366
        st_city_id_is_1080: 0.0584620042520658
        st_city_id_is_1085: 0.06250486587047303
        st_city_id_is_1090: -0.03662870298971974
        st_city_id_is_1095: 0.020438165618287846
        st_city_id_is_1100: -0.0014295446763022432
        st_city_id_is_1105: 0.03799306777173468
        st_city_id_is_1110: -0.13599358670446146
        st_city_id_is_1115: -0.11515717477412077
        st_city_id_is_1120: 0.11461550040457259
        st_city_id_is_1125: -0.015833370288284413
        st_city_id_is_1130: 0.042860671062479344
        st_city_id_is_1135: 0.05860968200019828
        st_city_id_is_1140: -0.11441113996949838
        st_city_id_is_1145: 0.046437437478431494
        st_city_id_is_1150: 0.10005125285732143
        st_city_id_is_1155: 0.04215715682600875
        st_city_id_is_1160: 0.03528552394836491
        st_city_id_is_1165: 0.02876158287424382
        st_city_id_is_1170: -0.06366215456150254
        st_city_id_is_1175: 0.0670657487474168
        st_city_id_is_1180: -0.007399189084775611
        st_city_id_is_1185: -0.14821549697145742
        st_city_id_is_1190: 0.02085168862288676
        st_city_id_is_1200: -0.07608525101499071
        st_city_id_is_1205: -0.00549065882215328
        st_city_id_is_1210: -0.016264654701964167
        st_city_id_is_1215: 0.11044768313276392
        st_city_id_is_1220: -0.007650971812121161
        st_jobs_within_30_min: -0.05463956707493248
        st_ln_empden: -0.04667011686828137
        st_ln_residential_units: 0.08418256822730802
        st_mean_zonal_hhsize: 0.062245393308022555
        st_mode_income_quartile_is_4: 0.07232641427183129
        st_popden: -0.051840675573497995
        st_zone_mean_age_of_head: 0.07439946717933565
        st_zone_prop_race_1: 0.09602140463597061
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0823725340405672
        st_building_age: 0.02471585474190185
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 0.030871552860345562
        st_ln_empden: 0.02635146291422208
        st_ln_residential_units: 0.00756913720221639
        st_mean_zonal_hhsize: 0.02626073011235936
        st_mode_income_quartile_is_4: 0.02453706262314756
        st_popden: 0.02143656908502235
        st_zone_mean_age_of_head: 0.02350513565759116
        st_zone_prop_race_1: 0.04047729876869192
    T-Score:
        st_b_ln_sqft_per_unit: 3.532008625536553
        st_building_age: -6.085560311895312
        st_city_id_is_1005: 0.0
        st_city_id_is_1010: 0.0
        st_city_id_is_1015: 0.0
        st_city_id_is_1020: 0.0
        st_city_id_is_1025: 0.0
        st_city_id_is_1030: 0.0
        st_city_id_is_1040: 0.0
        st_city_id_is_1045: 0.0
        st_city_id_is_1050: 0.0
        st_city_id_is_1055: 0.0
        st_city_id_is_1060: 0.0
        st_city_id_is_1065: 0.0
        st_city_id_is_1070: 0.0
        st_city_id_is_1075: 0.0
        st_city_id_is_1080: 0.0
        st_city_id_is_1085: 0.0
        st_city_id_is_1090: 0.0
        st_city_id_is_1095: 0.0
        st_city_id_is_1100: 0.0
        st_city_id_is_1105: 0.0
        st_city_id_is_1110: 0.0
        st_city_id_is_1115: 0.0
        st_city_id_is_1120: 0.0
        st_city_id_is_1125: 0.0
        st_city_id_is_1130: 0.0
        st_city_id_is_1135: 0.0
        st_city_id_is_1140: 0.0
        st_city_id_is_1145: 0.0
        st_city_id_is_1150: 0.0
        st_city_id_is_1155: 0.0
        st_city_id_is_1160: 0.0
        st_city_id_is_1165: 0.0
        st_city_id_is_1170: 0.0
        st_city_id_is_1175: 0.0
        st_city_id_is_1180: 0.0
        st_city_id_is_1185: 0.0
        st_city_id_is_1190: 0.0
        st_city_id_is_1200: 0.0
        st_city_id_is_1205: 0.0
        st_city_id_is_1210: 0.0
        st_city_id_is_1215: 0.0
        st_city_id_is_1220: 0.0
        st_jobs_within_30_min: 9.11323485356064
        st_ln_empden: 2.1330025152805097
        st_ln_residential_units: 52.3422281025035
        st_mean_zonal_hhsize: -13.422672330983838
        st_mode_income_quartile_is_4: 15.20787964973099
        st_popden: -1.7786272948261095
        st_zone_mean_age_of_head: -16.027169136856013
        st_zone_prop_race_1: 15.130039374309908

probability_mode: single_chooser

log_likelihoods:
    convergence: -11974.931499386737
    'null': -13815.510557964428
    ratio: 0.13322555477449405
