name: hlcm150125

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 15

choosers_predict_filters: hh_type_large_area_id == 150125

alts_fit_filters: (residential_units > 0)

alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)

interaction_predict_filters: null

choice_column: building_id

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_sqft_per_unit
- st_building_age
- st_city_id_is_2005
- st_city_id_is_2010
- st_city_id_is_2015
- st_city_id_is_2020
- st_city_id_is_2025
- st_city_id_is_2030
- st_city_id_is_2035
- st_city_id_is_2040
- st_city_id_is_2045
- st_city_id_is_2050
- st_city_id_is_2055
- st_city_id_is_2060
- st_city_id_is_2065
- st_city_id_is_2072
- st_city_id_is_2075
- st_city_id_is_2080
- st_city_id_is_2085
- st_city_id_is_2090
- st_city_id_is_2095
- st_city_id_is_2100
- st_city_id_is_2105
- st_city_id_is_2110
- st_city_id_is_2115
- st_city_id_is_2120
- st_city_id_is_2125
- st_city_id_is_2130
- st_city_id_is_2135
- st_city_id_is_2140
- st_city_id_is_2145
- st_city_id_is_2150
- st_city_id_is_2155
- st_city_id_is_2160
- st_city_id_is_2165
- st_city_id_is_2170
- st_city_id_is_2175
- st_city_id_is_2180
- st_city_id_is_2185
- st_city_id_is_2190
- st_city_id_is_2195
- st_city_id_is_2200
- st_city_id_is_2205
- st_city_id_is_2210
- st_city_id_is_2215
- st_city_id_is_2220
- st_city_id_is_2230
- st_city_id_is_2235
- st_city_id_is_2240
- st_city_id_is_2245
- st_city_id_is_2250
- st_city_id_is_2255
- st_city_id_is_2260
- st_city_id_is_2265
- st_city_id_is_2270
- st_city_id_is_2275
- st_city_id_is_2280
- st_city_id_is_2285
- st_city_id_is_2290
- st_city_id_is_2295
- st_city_id_is_2300
- st_jobs_within_30_min
- st_ln_empden
- st_ln_residential_units
- st_mean_zonal_hhsize
- st_mode_income_quartile_is_4
- st_popden
- st_zone_mean_age_of_head
- st_zone_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_sqft_per_unit: 0.06784140301876591
        st_building_age: 0.026922242850004646
        st_city_id_is_2005: 0.060141474375663855
        st_city_id_is_2010: -0.026457603362263275
        st_city_id_is_2015: 0.06320652039161144
        st_city_id_is_2020: 0.08551376943285072
        st_city_id_is_2025: 0.0584262011029819
        st_city_id_is_2030: 0.06170541180342637
        st_city_id_is_2035: 0.0639201197701458
        st_city_id_is_2040: 0.0671541327905726
        st_city_id_is_2045: 0.02449457658180769
        st_city_id_is_2050: 0.05298525057617986
        st_city_id_is_2055: 0.09089522297634267
        st_city_id_is_2060: -0.001008394658447762
        st_city_id_is_2065: 0.07761973797192549
        st_city_id_is_2072: 0.09205030465292321
        st_city_id_is_2075: 0.026646486789319874
        st_city_id_is_2080: 0.07524926642217371
        st_city_id_is_2085: 0.06069984097446934
        st_city_id_is_2090: 0.05705051377666216
        st_city_id_is_2095: -0.004999149812367303
        st_city_id_is_2100: 0.07021503357193586
        st_city_id_is_2105: 0.04897931730312151
        st_city_id_is_2110: 0.08418200944585744
        st_city_id_is_2115: -0.023584427914650083
        st_city_id_is_2120: 0.06881403358089727
        st_city_id_is_2125: 0.043891784564688105
        st_city_id_is_2130: 0.07034741484977144
        st_city_id_is_2135: 0.08330905290684586
        st_city_id_is_2140: 0.04199048388580536
        st_city_id_is_2145: -0.042590059730021786
        st_city_id_is_2150: 0.07384451684878963
        st_city_id_is_2155: 0.06587187196008608
        st_city_id_is_2160: 0.010615046334485791
        st_city_id_is_2165: 0.07072515686048066
        st_city_id_is_2170: -0.002260817620381904
        st_city_id_is_2175: -0.015161873492748095
        st_city_id_is_2180: 0.06446172031514842
        st_city_id_is_2185: 0.06993475048981514
        st_city_id_is_2190: -0.0017653953662953065
        st_city_id_is_2195: 0.06360064888772837
        st_city_id_is_2200: 0.06407814205689048
        st_city_id_is_2205: 0.020720732905108532
        st_city_id_is_2210: 0.07988422852792688
        st_city_id_is_2215: -0.06788736864881757
        st_city_id_is_2220: 0.019446815356696165
        st_city_id_is_2230: 0.08878682849302932
        st_city_id_is_2235: 0.05280197960694364
        st_city_id_is_2240: -0.2567671934561889
        st_city_id_is_2245: 0.05885897060285332
        st_city_id_is_2250: 0.07596416834910474
        st_city_id_is_2255: 0.08084119248249812
        st_city_id_is_2260: 0.06590434080441854
        st_city_id_is_2265: 0.06927689679501435
        st_city_id_is_2270: 0.007143871916820567
        st_city_id_is_2275: 0.06840191854008063
        st_city_id_is_2280: -0.016661062641455972
        st_city_id_is_2285: -0.010338817250942635
        st_city_id_is_2290: 0.06481614495337254
        st_city_id_is_2295: 0.02787668817961737
        st_city_id_is_2300: 0.07120620880652566
        st_jobs_within_30_min: -0.05309935063690175
        st_ln_empden: -0.00034771068869202614
        st_ln_residential_units: 0.009815757321685563
        st_mean_zonal_hhsize: 0.0317951093507068
        st_mode_income_quartile_is_4: 0.017257111315353166
        st_popden: -0.09606711823969374
        st_zone_mean_age_of_head: 0.09927154629191899
        st_zone_prop_race_1: 0.04894371468569261
    Std. Error:
        st_b_ln_sqft_per_unit: 0.0823725340405672
        st_building_age: 0.02471585474190185
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 0.030871552860345562
        st_ln_empden: 0.02635146291422208
        st_ln_residential_units: 0.00756913720221639
        st_mean_zonal_hhsize: 0.02626073011235936
        st_mode_income_quartile_is_4: 0.02453706262314756
        st_popden: 0.02143656908502235
        st_zone_mean_age_of_head: 0.02350513565759116
        st_zone_prop_race_1: 0.04047729876869192
    T-Score:
        st_b_ln_sqft_per_unit: 3.532008625536553
        st_building_age: -6.085560311895312
        st_city_id_is_2005: 0.0
        st_city_id_is_2010: 0.0
        st_city_id_is_2015: 0.0
        st_city_id_is_2020: 0.0
        st_city_id_is_2025: 0.0
        st_city_id_is_2030: 0.0
        st_city_id_is_2035: 0.0
        st_city_id_is_2040: 0.0
        st_city_id_is_2045: 0.0
        st_city_id_is_2050: 0.0
        st_city_id_is_2055: 0.0
        st_city_id_is_2060: 0.0
        st_city_id_is_2065: 0.0
        st_city_id_is_2072: 0.0
        st_city_id_is_2075: 0.0
        st_city_id_is_2080: 0.0
        st_city_id_is_2085: 0.0
        st_city_id_is_2090: 0.0
        st_city_id_is_2095: 0.0
        st_city_id_is_2100: 0.0
        st_city_id_is_2105: 0.0
        st_city_id_is_2110: 0.0
        st_city_id_is_2115: 0.0
        st_city_id_is_2120: 0.0
        st_city_id_is_2125: 0.0
        st_city_id_is_2130: 0.0
        st_city_id_is_2135: 0.0
        st_city_id_is_2140: 0.0
        st_city_id_is_2145: 0.0
        st_city_id_is_2150: 0.0
        st_city_id_is_2155: 0.0
        st_city_id_is_2160: 0.0
        st_city_id_is_2165: 0.0
        st_city_id_is_2170: 0.0
        st_city_id_is_2175: 0.0
        st_city_id_is_2180: 0.0
        st_city_id_is_2185: 0.0
        st_city_id_is_2190: 0.0
        st_city_id_is_2195: 0.0
        st_city_id_is_2200: 0.0
        st_city_id_is_2205: 0.0
        st_city_id_is_2210: 0.0
        st_city_id_is_2215: 0.0
        st_city_id_is_2220: 0.0
        st_city_id_is_2230: 0.0
        st_city_id_is_2235: 0.0
        st_city_id_is_2240: 0.0
        st_city_id_is_2245: 0.0
        st_city_id_is_2250: 0.0
        st_city_id_is_2255: 0.0
        st_city_id_is_2260: 0.0
        st_city_id_is_2265: 0.0
        st_city_id_is_2270: 0.0
        st_city_id_is_2275: 0.0
        st_city_id_is_2280: 0.0
        st_city_id_is_2285: 0.0
        st_city_id_is_2290: 0.0
        st_city_id_is_2295: 0.0
        st_city_id_is_2300: 0.0
        st_jobs_within_30_min: 9.11323485356064
        st_ln_empden: 2.1330025152805097
        st_ln_residential_units: 52.3422281025035
        st_mean_zonal_hhsize: -13.422672330983838
        st_mode_income_quartile_is_4: 15.20787964973099
        st_popden: -1.7786272948261095
        st_zone_mean_age_of_head: -16.027169136856013
        st_zone_prop_race_1: 15.130039374309908

probability_mode: single_chooser

log_likelihoods:
    convergence: -11974.931499386737
    'null': -13815.510557964428
    ratio: 0.13322555477449405
