alts_fit_filters: (residential_units >0) & (large_area_id == 125)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 125)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 120125)
choosers_predict_filters: hh_type_large_area_id == 120125
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.04672910458758911
    st_zones_popden: 0.1666823980342206
    st_zones_prop_hh_with_children: -0.0007523058623022509
    st_zones_prop_income_2: 0.27322996644705017
    st_zones_prop_income_3: 0.12146123393217499
    st_zones_prop_race_1: 0.6819840021049881
  Std. Error:
    st_b_ln_residential_units: 0.006798641615886049
    st_zones_popden: 0.01595403549787568
    st_zones_prop_hh_with_children: 0.021293069166121767
    st_zones_prop_income_2: 0.02536549231601223
    st_zones_prop_income_3: 0.02794895138979666
    st_zones_prop_race_1: 0.033553927058518375
  T-Score:
    st_b_ln_residential_units: -6.873300171963694
    st_zones_popden: 10.447663730998642
    st_zones_prop_hh_with_children: -0.03533102045707922
    st_zones_prop_income_2: 10.771719430597091
    st_zones_prop_income_3: 4.3458243652216915
    st_zones_prop_race_1: 20.325012953494277
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -13260.84923823264
  'null': -13815.510557964428
  ratio: 0.04014772508078135
model_expression:
- st_b_ln_residential_units
- st_zones_popden
- st_zones_prop_income_3
- st_zones_prop_income_2
- st_zones_prop_hh_with_children
- st_zones_prop_race_1
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
