alts_fit_filters: (residential_units >0) & (large_area_id == 93)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 93)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 90093)
choosers_predict_filters: hh_type_large_area_id == 90093
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: 0.038194722600644465
    st_b_ln_sqft_per_unit: 0.13201762518242227
    st_zones_households: 0.13363081932683066
    st_zones_mean_age_of_head: -0.30470901995195476
    st_zones_mean_hh_size: -0.38624779801936604
    st_zones_prop_income_2: 0.1709903914938641
    st_zones_prop_income_3: 0.24856424997195203
    st_zones_prop_race_1: 0.3615924620632033
    st_zones_prop_race_3: 0.0031043594171561665
  Std. Error:
    st_b_ln_residential_units: 0.006193392817327115
    st_b_ln_sqft_per_unit: 0.10099675527052064
    st_zones_households: 0.02083334379193313
    st_zones_mean_age_of_head: 0.018580963914690794
    st_zones_mean_hh_size: 0.027790626375937707
    st_zones_prop_income_2: 0.02613011951926456
    st_zones_prop_income_3: 0.026717306275585734
    st_zones_prop_race_1: 0.03209150603083557
    st_zones_prop_race_3: 0.033174824086662065
  T-Score:
    st_b_ln_residential_units: 6.167011156435606
    st_b_ln_sqft_per_unit: 1.3071471932817245
    st_zones_households: 6.414276107639225
    st_zones_mean_age_of_head: -16.398988844224633
    st_zones_mean_hh_size: -13.898491987708331
    st_zones_prop_income_2: 6.543804415735665
    st_zones_prop_income_3: 9.303492178741461
    st_zones_prop_race_1: 11.267544181808175
    st_zones_prop_race_3: 0.09357576121720187
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -12981.381520171843
  'null': -13815.510557964428
  ratio: 0.060376273051430784
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_households
- st_zones_prop_income_3
- st_zones_prop_income_2
- st_zones_mean_age_of_head
- st_zones_mean_hh_size
- st_zones_prop_race_1
- st_zones_prop_race_3
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
