alts_fit_filters: (residential_units >0) & (large_area_id == 161)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 161)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 70161)
choosers_predict_filters: hh_type_large_area_id == 70161
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.056774578666145714
    st_b_ln_sqft_per_unit: 0.8615518985490819
    st_zones_mean_age_of_head: 0.2835149318144267
    st_zones_prop_income_2: 0.2258920856802552
    st_zones_prop_income_3: 0.1551535818889108
    st_zones_prop_race_1: 0.3933622389081343
    st_zones_prop_race_2: -0.05559736518429829
  Std. Error:
    st_b_ln_residential_units: 0.007505849101289796
    st_b_ln_sqft_per_unit: 0.07433116920431534
    st_zones_mean_age_of_head: 0.028833816525146484
    st_zones_prop_income_2: 0.024306028493723632
    st_zones_prop_income_3: 0.028233070570709333
    st_zones_prop_race_1: 0.11619053995041172
    st_zones_prop_race_2: 0.1162297814646273
  T-Score:
    st_b_ln_residential_units: -7.564044773613905
    st_b_ln_sqft_per_unit: 11.59072173586991
    st_zones_mean_age_of_head: 9.832723030860944
    st_zones_prop_income_2: 9.293664974456261
    st_zones_prop_income_3: 5.495455462427681
    st_zones_prop_race_1: 3.3854928213262037
    st_zones_prop_race_2: -0.47834009910117975
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -13211.776580988962
  'null': -13815.510557964428
  ratio: 0.043699722456324475
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_prop_income_3
- st_zones_prop_income_2
- st_zones_mean_age_of_head
- st_zones_prop_race_1
- st_zones_prop_race_2
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
