alts_fit_filters: (residential_units >0) & (large_area_id == 115)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 115)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 160115)
choosers_predict_filters: hh_type_large_area_id == 160115
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_building_sqft: -0.730494696081241
    st_b_ln_residential_units: 0.30035219465251506
    st_b_ln_sqft_per_unit: 3.0
    st_zones_logsum_pop_high_income: 0.034099901164107244
    st_zones_mean_age_of_head: 0.36107321072620213
    st_zones_mean_hh_size: -0.03288870602253758
    st_zones_prop_income_4: 0.42685909852618037
    st_zones_prop_race_1: 0.11978816337666083
    st_zones_sum_residential_units: -0.04813518995071815
  Std. Error:
    st_b_ln_building_sqft: 0.08734967478864566
    st_b_ln_residential_units: 0.04645353117918709
    st_b_ln_sqft_per_unit: 0.14861579096190802
    st_zones_logsum_pop_high_income: 0.05055347802131223
    st_zones_mean_age_of_head: 0.04863719975795346
    st_zones_mean_hh_size: 0.05359901670202554
    st_zones_prop_income_4: 0.05532697508253018
    st_zones_prop_race_1: 0.05926914451616158
    st_zones_sum_residential_units: 0.043202283052690575
  T-Score:
    st_b_ln_building_sqft: -8.362878257403608
    st_b_ln_residential_units: 6.465648294721759
    st_b_ln_sqft_per_unit: 20.186280210081684
    st_zones_logsum_pop_high_income: 0.6745312587539769
    st_zones_mean_age_of_head: 7.423807549018221
    st_zones_mean_hh_size: -0.6136065182944801
    st_zones_prop_income_4: 7.715207597911198
    st_zones_prop_race_1: 2.021088111774531
    st_zones_sum_residential_units: -1.1141816253555694
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -4156.4830294661315
  'null': -4517.671952454357
  ratio: 0.07995023250681121
model_expression:
- st_b_ln_residential_units
- st_b_ln_building_sqft
- st_b_ln_sqft_per_unit
- st_zones_sum_residential_units
- st_zones_prop_income_4
- st_zones_mean_age_of_head
- st_zones_logsum_pop_high_income
- st_zones_mean_hh_size
- st_zones_prop_race_1
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
