alts_fit_filters: (residential_units >0) & (large_area_id == 5)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 140005)
choosers_predict_filters: hh_type_large_area_id == 140005
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.10540521498522046
    st_b_ln_sqft_per_unit: 0.9681021594526534
    st_zones_mean_hh_size: -0.49771818627771197
    st_zones_prop_income_4: 0.705119037276609
    st_zones_prop_race_1: 0.4835059713786014
    st_zones_sum_residential_units: -0.01909384857118373
  Std. Error:
    st_b_ln_residential_units: 0.012135341122723645
    st_b_ln_sqft_per_unit: 0.1015307943502345
    st_zones_mean_hh_size: 0.038578520324600546
    st_zones_prop_income_4: 0.04066770956616721
    st_zones_prop_race_1: 0.05074537149316496
    st_zones_sum_residential_units: 0.02617033702325628
  T-Score:
    st_b_ln_residential_units: -8.685805690937464
    st_b_ln_sqft_per_unit: 9.535059443277344
    st_zones_mean_hh_size: -12.901432768543216
    st_zones_prop_income_4: 17.33854807164307
    st_zones_prop_race_1: 9.528080239667302
    st_zones_sum_residential_units: -0.729598879609994
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -7551.5952606165165
  'null': -8420.553685079312
  ratio: 0.10319492719374679
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_sum_residential_units
- st_zones_prop_income_4
- st_zones_mean_hh_size
- st_zones_prop_race_1
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
