alts_fit_filters: (residential_units >0) & (large_area_id == 147)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 147)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 40147)
choosers_predict_filters: hh_type_large_area_id == 40147
estimation_sample_size: 1000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.015542301956634684
    st_b_ln_sqft_per_unit: 0.3260902994425985
    st_zones_prop_income_1: 0.3242461982076319
    st_zones_prop_race_1: 0.26508835789146695
  Std. Error:
    st_b_ln_residential_units: 0.01024144594211878
    st_b_ln_sqft_per_unit: 0.1668500725427348
    st_zones_prop_income_1: 0.051121163547182005
    st_zones_prop_race_1: 0.050223940074624766
  T-Score:
    st_b_ln_residential_units: -1.5175886339169844
    st_b_ln_sqft_per_unit: 1.9543911157669889
    st_zones_prop_income_1: 6.342699886092588
    st_zones_prop_race_1: 5.2781274726273555
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -3266.005274722284
  'null': -3281.313075966889
  ratio: 0.0046651449862321615
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_prop_income_1
- st_zones_prop_race_1
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 500
