alts_fit_filters: (residential_units >0) & (large_area_id == 99)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 99)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 20099)
choosers_predict_filters: hh_type_large_area_id == 20099
estimation_sample_size: 1000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.02429421789199013
    st_b_ln_sqft_per_unit: -0.1919002311460565
    st_zones_mean_hh_size: -0.29964642959878873
    st_zones_prop_income_1: 0.06559585844597005
    st_zones_prop_race_4: 0.0019366723472190673
  Std. Error:
    st_b_ln_residential_units: 0.008903228238293665
    st_b_ln_sqft_per_unit: 0.12902044199021487
    st_zones_mean_hh_size: 0.033917152330561445
    st_zones_prop_income_1: 0.02766698147806125
    st_zones_prop_race_4: 0.03126441190721651
  T-Score:
    st_b_ln_residential_units: -2.728697641098124
    st_b_ln_sqft_per_unit: -1.4873629960174106
    st_zones_mean_hh_size: -8.83465765870883
    st_zones_prop_income_1: 2.3709076647188563
    st_zones_prop_race_4: 0.06194494727636444
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -6166.63611517258
  'null': -6214.608098422123
  ratio: 0.007719229030986319
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_prop_income_1
- st_zones_mean_hh_size
- st_zones_prop_race_4
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 500
