alts_fit_filters: (residential_units >0) & (large_area_id == 3)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 3)
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 100003)
choosers_predict_filters: hh_type_large_area_id == 100003
estimation_sample_size: 2000
fit_parameters:
  Coefficient:
    st_b_ln_residential_units: -0.12956568516099
    st_b_ln_sqft_per_unit: 0.8264745249835269
    st_zones_mean_age_of_head: 0.45858116861123815
    st_zones_mean_hh_size: 0.10325438307776873
    st_zones_prop_income_1: 0.06450841023534898
    st_zones_prop_income_3: 0.34217874763745737
    st_zones_prop_race_1: -0.014706920452816423
  Std. Error:
    st_b_ln_residential_units: 0.010523247695063558
    st_b_ln_sqft_per_unit: 0.08036455385261057
    st_zones_mean_age_of_head: 0.0326828725663534
    st_zones_mean_hh_size: 0.02594789575548025
    st_zones_prop_income_1: 0.04162614380003173
    st_zones_prop_income_3: 0.03359069344314248
    st_zones_prop_race_1: 0.030335522785445674
  T-Score:
    st_b_ln_residential_units: -12.312328752060935
    st_b_ln_sqft_per_unit: 10.284067855329475
    st_zones_mean_age_of_head: 14.03123815632233
    st_zones_mean_hh_size: 3.9792969746289035
    st_zones_prop_income_1: 1.5497090132884181
    st_zones_prop_income_3: 10.186712823200528
    st_zones_prop_race_1: -0.48480853805731955
fitted: true
interaction_predict_filters: null
log_likelihoods:
  convergence: -12383.469481082668
  'null': -12889.87135058081
  ratio: 0.039286805564225036
model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_prop_income_3
- st_zones_prop_income_1
- st_zones_mean_age_of_head
- st_zones_mean_hh_size
- st_zones_prop_race_1
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
