name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id>1) & (qlid == 200147)

choosers_predict_filters: qlid == 200147

alts_fit_filters: (residential_units>0) & (large_area_id == 147)

alts_predict_filters: large_area_id == 147

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: 2000

prediction_sample_size: 100

model_expression: is_young:nodes_walk_retail_jobs + ln_income:nodes_walk_ln_popden
    + has_children:nodes_walk_percent_hh_with_children + is_race1:nodes_walk_percent_race1
    + nodes_drv_drv_15min_retail_jobs

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        has_children:nodes_walk_percent_hh_with_children: 3.0
        is_race1:nodes_walk_percent_race1: 2.4845015769427405
        is_young:nodes_walk_retail_jobs: 0.0037483701621176557
        ln_income:nodes_walk_ln_popden: 0.012007174767009474
        nodes_drv_drv_15min_retail_jobs: 0.014927753697084168
    Std. Error:
        has_children:nodes_walk_percent_hh_with_children: 0.23885440522607795
        is_race1:nodes_walk_percent_race1: 0.2036448457020912
        is_young:nodes_walk_retail_jobs: 0.002309451324205781
        ln_income:nodes_walk_ln_popden: 0.0038536215970970413
        nodes_drv_drv_15min_retail_jobs: 0.020318476886679752
    T-Score:
        has_children:nodes_walk_percent_hh_with_children: 12.55995256675493
        is_race1:nodes_walk_percent_race1: 12.200169213107795
        is_young:nodes_walk_retail_jobs: 1.6230565774780805
        ln_income:nodes_walk_ln_popden: 3.1158157241111994
        nodes_drv_drv_15min_retail_jobs: 0.73468861767244

probability_mode: full_product

log_likelihoods:
    convergence: -4353.814361287637
    'null': -4382.026634673841
    ratio: 0.006438179349017914
