name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id>1) & (qlid == 100161)

choosers_predict_filters: qlid == 100161

alts_fit_filters: (residential_units>0) & (large_area_id == 161)

alts_predict_filters: large_area_id == 161

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: 2000

prediction_sample_size: 100

model_expression:
- residential_units
- has_children:nodes_walk_percent_hh_with_children
- zones_employment
- has_workers:zones_a_ln_emp_50min_transit
- nodes_drv_drv_60min_jobs
- persons:nodes_walk_ln_popden
- nodes_walk_ave_lot_sqft
- is_young:zones_empden
- is_race2:nodes_walk_percent_race2
- ln_income:nodes_walk_ln_popden
- zones_transit_jobs_30min

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        has_children:nodes_walk_percent_hh_with_children: 3.0
        has_workers:zones_a_ln_emp_50min_transit: 0.0554337824151162
        is_race2:nodes_walk_percent_race2: 3.0
        is_young:zones_empden: 0.009939312946705497
        ln_income:nodes_walk_ln_popden: 0.04706271757540082
        nodes_drv_drv_60min_jobs: 0.4168216189274129
        nodes_walk_ave_lot_sqft: 1.0509374263751579
        persons:nodes_walk_ln_popden: 0.1002420171346053
        residential_units: 0.04458856588654314
        zones_employment: 1.1263297711090434e-05
        zones_transit_jobs_30min: 5.928794979545127e-06
    Std. Error:
        has_children:nodes_walk_percent_hh_with_children: 0.3740295855323743
        has_workers:zones_a_ln_emp_50min_transit: 0.0070704887336856615
        is_race2:nodes_walk_percent_race2: 0.29116683716135777
        is_young:zones_empden: 0.003276906115950965
        ln_income:nodes_walk_ln_popden: 0.004575811753156299
        nodes_drv_drv_60min_jobs: 0.029160157743520976
        nodes_walk_ave_lot_sqft: 0.049531865922416304
        persons:nodes_walk_ln_popden: 0.012541656428931134
        residential_units: 0.0013124486188961912
        zones_employment: 2.951647371144642e-05
        zones_transit_jobs_30min: 1.625406900892555e-06
    T-Score:
        has_children:nodes_walk_percent_hh_with_children: 8.02075588681028
        has_workers:zones_a_ln_emp_50min_transit: 7.840162752967151
        is_race2:nodes_walk_percent_race2: 10.303371184876632
        is_young:zones_empden: 3.033139368358464
        ln_income:nodes_walk_ln_popden: 10.285107892154423
        nodes_drv_drv_60min_jobs: 14.294216876108136
        nodes_walk_ave_lot_sqft: 21.217400289770673
        persons:nodes_walk_ln_popden: 7.992725498632437
        residential_units: 33.97357065607907
        zones_employment: 0.3815936084100234
        zones_transit_jobs_30min: 3.6475758631819915

probability_mode: full_product

log_likelihoods:
    convergence: -3063.6598243894578
    'null': -4382.026634673841
    ratio: 0.3008577811582632
