name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id>1) & (qlid == 400115)

choosers_predict_filters: qlid == 400115

alts_fit_filters: (residential_units>0) & (large_area_id == 115)

alts_predict_filters: large_area_id == 115

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: 2000

prediction_sample_size: 100

model_expression:
- ln_income:nodes_walk_ave_income
- persons:sqft_per_unit
- has_children:sqft_per_unit
- vacant_residential_units
- nodes_walk_ave_lot_sqft
- building_type_id_is_84
- nodes_walk_race_3_hhs

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        building_type_id_is_84: -0.3941309594371651
        has_children:sqft_per_unit: 0.00010159776149988903
        ln_income:nodes_walk_ave_income: 0.1235809698109329
        nodes_walk_ave_lot_sqft: 0.4417455542548669
        nodes_walk_race_3_hhs: 0.01807196984804555
        persons:sqft_per_unit: 1.8239025889504824e-05
        vacant_residential_units: -0.00561679020686296
    Std. Error:
        building_type_id_is_84: 0.179886519050685
        has_children:sqft_per_unit: 2.7490089476472526e-05
        ln_income:nodes_walk_ave_income: 0.004278066257975021
        nodes_walk_ave_lot_sqft: 0.07525427476756374
        nodes_walk_race_3_hhs: 0.011438533568908149
        persons:sqft_per_unit: 7.68273337865604e-06
        vacant_residential_units: 0.034265332135467334
    T-Score:
        building_type_id_is_84: -2.1909977552354234
        has_children:sqft_per_unit: 3.6957959553693622
        ln_income:nodes_walk_ave_income: 28.88710981989996
        nodes_walk_ave_lot_sqft: 5.870039351508959
        nodes_walk_race_3_hhs: 1.5799201653932453
        persons:sqft_per_unit: 2.374028225445905
        vacant_residential_units: -0.16392049505480022

probability_mode: full_product

log_likelihoods:
    convergence: -4205.539755674028
    'null': -4382.026634673841
    ratio: 0.04027517258870994
