name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id>1) & (qlid == 400125)

choosers_predict_filters: qlid == 400125

alts_fit_filters: (residential_units>0) & (large_area_id == 125)

alts_predict_filters: large_area_id == 125

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: 2000

prediction_sample_size: 100

model_expression:
- zones_logsum_job_high_income
- walk_nearest_healthcenter
- has_children:nodes_walk_percent_hh_with_children
- ln_income:nodes_walk_ave_income
- persons:sqft_per_unit
- building_age_le_10
- is_young:zones_empden
- is_race2:nodes_walk_percent_race2
- parcels_total_units

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        building_age_le_10: 0.260537747858736
        has_children:nodes_walk_percent_hh_with_children: 1.8932618507608336
        is_race2:nodes_walk_percent_race2: 3.0
        is_young:zones_empden: 0.03156603560811767
        ln_income:nodes_walk_ave_income: 0.08471659205709925
        parcels_total_units: 0.0017667616435269795
        persons:sqft_per_unit: 3.329659629403504e-05
        walk_nearest_healthcenter: 2.0399208750555435e-06
        zones_logsum_job_high_income: 4.6907264939181714e-07
    Std. Error:
        building_age_le_10: 0.12127394673823894
        has_children:nodes_walk_percent_hh_with_children: 0.15878176688884843
        is_race2:nodes_walk_percent_race2: 0.21553709317329628
        is_young:zones_empden: 0.007258780799873437
        ln_income:nodes_walk_ave_income: 0.001578919399374606
        parcels_total_units: 0.0002151501216262315
        persons:sqft_per_unit: 5.583248723319796e-06
        walk_nearest_healthcenter: 2.084488602824513e-05
        zones_logsum_job_high_income: 1.428964993406835e-07
    T-Score:
        building_age_le_10: 2.1483406359412704
        has_children:nodes_walk_percent_hh_with_children: 11.923672899333388
        is_race2:nodes_walk_percent_race2: 13.918717914544473
        is_young:zones_empden: 4.348669077962521
        ln_income:nodes_walk_ave_income: 53.654792062631344
        parcels_total_units: 8.211762234540018
        persons:sqft_per_unit: 5.963659858992796
        walk_nearest_healthcenter: 0.09786193468707004
        zones_logsum_job_high_income: 3.2826042034345995

probability_mode: full_product

log_likelihoods:
    convergence: -8371.037433641959
    'null': -8764.053269347662
    ratio: 0.0448440719866775
