name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: building_id>1

choosers_predict_filters: qlid == 100099

alts_fit_filters: (residential_units>0) & (large_area_id == 99)

alts_predict_filters: null

interaction_predict_filters: null

choice_column: building_id

sample_size: 80

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- residential_units
- building_age_gt_70
- nodes_walk_retail_jobs
- nodes_walk_race_1_hhs
- vacant_residential_units
- persons:nodes_walk_ln_popden
- nodes_walk_ave_lot_sqft
- is_young:zones_empden
- is_race2:nodes_walk_percent_race2
- ln_income:nodes_walk_ln_popden
- zones_a_ln_retail_emp_15min_drive_alone

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        building_age_gt_70: 0.29650818378743626
        is_race2:nodes_walk_percent_race2: 3.0
        is_young:zones_empden: 0.09702455098559358
        ln_income:nodes_walk_ln_popden: 0.04690785884435618
        nodes_walk_ave_lot_sqft: 0.7202426573189536
        nodes_walk_race_1_hhs: 0.0011240694208682375
        nodes_walk_retail_jobs: 0.0009911146818406158
        persons:nodes_walk_ln_popden: 0.10589457022139037
        residential_units: 0.06300449900439939
        vacant_residential_units: -0.07614949067481794
        zones_a_ln_retail_emp_15min_drive_alone: 0.03676011888139612
    Std. Error:
        building_age_gt_70: 0.08912369084945981
        is_race2:nodes_walk_percent_race2: 0.23827900046461822
        is_young:zones_empden: 0.012841532212438025
        ln_income:nodes_walk_ln_popden: 0.0036213753044072312
        nodes_walk_ave_lot_sqft: 0.028373133569791233
        nodes_walk_race_1_hhs: 0.00017977021927024356
        nodes_walk_retail_jobs: 0.000452383447934349
        persons:nodes_walk_ln_popden: 0.007078168919947015
        residential_units: 0.001339024570509634
        vacant_residential_units: 0.01011824142076459
        zones_a_ln_retail_emp_15min_drive_alone: 0.0213520017330263
    T-Score:
        building_age_gt_70: 3.3269289115087566
        is_race2:nodes_walk_percent_race2: 12.590282795170053
        is_young:zones_empden: 7.555527594411027
        ln_income:nodes_walk_ln_popden: 12.953050954776515
        nodes_walk_ave_lot_sqft: 25.384670873498205
        nodes_walk_race_1_hhs: 6.252812203440968
        nodes_walk_retail_jobs: 2.1908730002527608
        persons:nodes_walk_ln_popden: 14.960729451224097
        residential_units: 47.052533905647316
        vacant_residential_units: -7.525961034942736
        zones_a_ln_retail_emp_15min_drive_alone: 1.7216240116980344

probability_mode: single_chooser

log_likelihoods:
    convergence: -7381.400433790638
    'null': -8764.053269347662
    ratio: 0.15776408393053265
