name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: building_id>1

choosers_predict_filters: qlid == 200125

alts_fit_filters: (residential_units>0) & (large_area_id == 125)

alts_predict_filters: large_area_id == 125

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: 2000

prediction_sample_size: 100

model_expression:
- walk_nearest_healthcenter
- has_children:nodes_walk_percent_hh_with_children
- vacant_residential_units
- nodes_walk_sum_residential_units
- building_type_id_is_82
- is_race1:nodes_walk_percent_race1
- nodes_walk_ave_lot_sqft
- ln_income:sqft_price_res
- is_young:zones_empden
- ln_income:nodes_walk_ln_popden
- nodes_drv_drv_30min_jobs

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        building_type_id_is_82: -0.4470569331430501
        has_children:nodes_walk_percent_hh_with_children: 2.216176538195264
        is_race1:nodes_walk_percent_race1: 3.0
        is_young:zones_empden: 0.006778573048300407
        ln_income:nodes_walk_ln_popden: 0.05446282551886875
        ln_income:sqft_price_res: -0.0008162730717848828
        nodes_drv_drv_30min_jobs: 0.06417451037722763
        nodes_walk_ave_lot_sqft: 0.9374301927270071
        nodes_walk_sum_residential_units: 0.06176316801898581
        vacant_residential_units: 0.024697074569789437
        walk_nearest_healthcenter: -4.551031343333095e-05
    Std. Error:
        building_type_id_is_82: 0.11820640719079968
        has_children:nodes_walk_percent_hh_with_children: 0.26781059889323294
        is_race1:nodes_walk_percent_race1: 0.13394572686502887
        is_young:zones_empden: 0.013011754353338739
        ln_income:nodes_walk_ln_popden: 0.006775762777360162
        ln_income:sqft_price_res: 5.641170855320863e-05
        nodes_drv_drv_30min_jobs: 0.028797022669108902
        nodes_walk_ave_lot_sqft: 0.0457676881293797
        nodes_walk_sum_residential_units: 0.043465474589235616
        vacant_residential_units: 0.00696813432063375
        walk_nearest_healthcenter: 2.3162875121914627e-05
    T-Score:
        building_type_id_is_82: -3.7820025476406305
        has_children:nodes_walk_percent_hh_with_children: 8.275163669227217
        is_race1:nodes_walk_percent_race1: 22.397131063561037
        is_young:zones_empden: 0.5209576559951783
        ln_income:nodes_walk_ln_popden: 8.03788847225367
        ln_income:sqft_price_res: -14.469922870975589
        nodes_drv_drv_30min_jobs: 2.228511992875875
        nodes_walk_ave_lot_sqft: 20.482358428876847
        nodes_walk_sum_residential_units: 1.4209707498346673
        vacant_residential_units: 3.544287959067822
        walk_nearest_healthcenter: -1.964795527057571

probability_mode: full_product

log_likelihoods:
    convergence: -3831.18359650812
    'null': -4382.026634673841
    ratio: 0.12570508673019987
