alts_fit_filters: (residential_units >0) & (large_area_id == 115)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 115)
choice_column: null
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 180115)
choosers_predict_filters: hh_type_large_area_id == 180115
estimation_sample_size: 2000
fit_parameters:
  Coefficient: {st_b_ln_residential_units: 0.10217655472222242, st_b_ln_sqft_per_unit: -0.5398923397358193,
    st_jobs_within_30_min: 0.19151854068761967, st_zones_mean_age_of_head: -0.5286290629581305,
    st_zones_mean_hh_size: -0.0763921203478358, st_zones_prop_income_4: 1.0330701107899491,
    st_zones_prop_race_1: 0.21099968499675598, st_zones_sum_residential_units: 0.15800803320348186}
  Std. Error: {st_b_ln_residential_units: 0.02714582048161745, st_b_ln_sqft_per_unit: 0.7915407868178372,
    st_jobs_within_30_min: 0.1717140964615274, st_zones_mean_age_of_head: 0.09372123911179542,
    st_zones_mean_hh_size: 0.15707124890974228, st_zones_prop_income_4: 0.181044593131268,
    st_zones_prop_race_1: 0.2164497548180983, st_zones_sum_residential_units: 0.12290230294583128}
  T-Score: {st_b_ln_residential_units: 3.763988448660601, st_b_ln_sqft_per_unit: -0.6820777257812597,
    st_jobs_within_30_min: 1.1153338289295862, st_zones_mean_age_of_head: -5.640440395026736,
    st_zones_mean_hh_size: -0.4863533006714229, st_zones_prop_income_4: 5.706163840203239,
    st_zones_prop_race_1: 0.9748206237243258, st_zones_sum_residential_units: 1.285639320144581}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -474.399539083166, 'null': -524.9894012026414, ratio: 0.09636358753830943}
model_expression: [st_b_ln_residential_units, st_b_ln_sqft_per_unit, st_zones_sum_residential_units,
  st_jobs_within_30_min, st_zones_prop_income_4, st_zones_mean_age_of_head, st_zones_mean_hh_size,
  st_zones_prop_race_1]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
