alts_fit_filters: (residential_units >0) & (large_area_id == 161)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 161)
choice_column: null
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (hh_type_large_area_id == 90161)
choosers_predict_filters: hh_type_large_area_id == 90161
estimation_sample_size: 2000
fit_parameters:
  Coefficient: {st_b_ln_residential_units: 0.0908962343883846, st_b_ln_sqft_per_unit: 0.1519725926802167,
    st_zones_empden: -0.0001964925843104118, st_zones_households: 0.05934895200570423,
    st_zones_mean_age_of_head: -0.33473016352833357, st_zones_mean_hh_size: -0.3574871242442066,
    st_zones_prop_income_2: 0.17698160924011586, st_zones_prop_income_3: 0.1392751201911104,
    st_zones_prop_race_1: 0.20645392761496384, st_zones_prop_race_3: -0.09416591627278231}
  Std. Error: {st_b_ln_residential_units: 0.016596047323770343, st_b_ln_sqft_per_unit: 0.3733548138790576,
    st_zones_empden: 0.010835435822362186, st_zones_households: 0.059886813628323265,
    st_zones_mean_age_of_head: 0.04726211387197292, st_zones_mean_hh_size: 0.08616313848825849,
    st_zones_prop_income_2: 0.0876446982332134, st_zones_prop_income_3: 0.07492869513140282,
    st_zones_prop_race_1: 0.08756971622048616, st_zones_prop_race_3: 0.13525086443564785}
  T-Score: {st_b_ln_residential_units: 5.476980910882007, st_b_ln_sqft_per_unit: 0.4070460244003867,
    st_zones_empden: -0.01813425759071824, st_zones_households: 0.9910186969379073,
    st_zones_mean_age_of_head: -7.082420486630691, st_zones_mean_hh_size: -4.148956624797524,
    st_zones_prop_income_2: 2.019307645616923, st_zones_prop_income_3: 1.8587687927417251,
    st_zones_prop_race_1: 2.3575950285729688, st_zones_prop_race_3: -0.6962315299477166}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -1541.2574787409208, 'null': -1685.4922880716465, ratio: 0.08557429206380007}
model_expression: [st_b_ln_residential_units, st_b_ln_sqft_per_unit, st_zones_empden,
  st_zones_households, st_zones_prop_income_3, st_zones_prop_income_2, st_zones_mean_age_of_head,
  st_zones_mean_hh_size, st_zones_prop_race_1, st_zones_prop_race_3]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
